"use strict";
const KEY="autoscuola_v3_completa";
const LIST_KEY="autoscuola_v3_checklists_v2";
const EXAMINERS_KEY="autoscuola_v3_examiners";
const LABELS={auto:"Auto",moto:"Moto","quad-leggero":"Quadriciclo leggero AM","quad-pesante":"Quadriciclo pesante B1","corso-moto":"Corso Moto ad accesso graduale A2 e A",perfezionamento:"Perfezionamento","esame-revisione":"Esame Revisione","esame-esperimento":"Esame Esperimento"};
const DEFAULT_LISTS={
 auto:["Spiegazione auto","Posizione mani sul volante","Uso cambio","Uso frizione","Uso volante","Partenza in salita","Extraurbana","Nervi Quinto Quarto","Autostrada Nervi","Autostrada Recco","Autostrada Rapallo","Autostrada Chiavari","Autostrada Est","Autostrada Bolzaneto","Autostrada Aeroporto","Autostrada Ovest","Park a L","Park a S","Park di punta","Retromarcia lunga","Inversioni di marcia"],
 moto:["Piazzale Marassi","Via Dodecaneso","Albaro","Villa Bombrini birilli lento","Villa Bombrini birilli veloce","Inversione IKEA","Inversione Villa Bombrini","Inversione Borzoli","Inversione Ponte Morandi","Cornigliano Budello","Cornigliano Via","Sampierdarena Anania","Corso Perrone","Ponte Morandi","Borzoli ingresso parcheggio","Borzoli strada chiusa","Borzoli Sestri","IKEA","Fiumara","Guido Rossa"],
 "quad-leggero":["Villa Bombrini percorso birilli"],
 "quad-pesante":["Villa Bombrini percorso birilli"],
 "corso-moto":["3 ore teoria + Villa Bombrini","2 ore Guido Rossa","2 ore Bargagli"],
 "esame-revisione":[],
 "esame-esperimento":[]
};
const STATES=["none","repeat","good"];
function loadLists(){const merged=JSON.parse(JSON.stringify(DEFAULT_LISTS));try{const x=JSON.parse(localStorage.getItem(LIST_KEY));if(x&&typeof x==="object")Object.keys(merged).forEach(k=>{if(Array.isArray(x[k]))merged[k]=x[k]})}catch{}return merged}
let LISTS=loadLists();
function saveLists(){localStorage.setItem(LIST_KEY,JSON.stringify(LISTS))}
const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"_"+Math.random();
let state={students:load(),examiners:loadExaminers(),studentId:null,lessonId:null,editingStudent:null,examinerId:null,editingExaminer:null,habitDraft:[],filter:"all",managerType:"auto",watch:null,tempRoute:[],liveMap:null,liveLine:null,liveMarker:null,savedMap:null,savedLine:null,recognition:null,recognizing:false};
function typeOf(c){return c==="perfezionamento"?"auto":(LISTS[c]?c:"auto")}
function loadExaminers(){try{const a=JSON.parse(localStorage.getItem(EXAMINERS_KEY)||"[]");return Array.isArray(a)?a.map(x=>({id:String(x.id||uid()),firstName:String(x.firstName||""),lastName:String(x.lastName||""),habits:Array.isArray(x.habits)?x.habits.map(String):[]})):[]}catch{return []}}
function saveExaminers(){localStorage.setItem(EXAMINERS_KEY,JSON.stringify(state.examiners))}
function oldStatus(x){if(x?.status&&STATES.includes(x.status))return x.status;return x?.done?"good":"none"}
function normalizeItems(items,type){const byLabel=new Map((items||[]).map(x=>[x.label,oldStatus(x)]));return LISTS[type].map(label=>({id:uid(),label,status:byLabel.get(label)||"none"}))}
function normalizeStudent(s){const c=LABELS[s.category]?s.category:"auto",t=typeOf(c);return{id:String(s.id||uid()),category:c,firstName:String(s.firstName||""),lastName:String(s.lastName||""),phone:String(s.phone||""),license:String(s.license||""),notes:String(s.notes||s.studentNotes||""),checklist:normalizeItems(s.checklist,t),lessons:Array.isArray(s.lessons)?s.lessons.map(l=>normalizeLesson(l,t)):[]}}
function normalizeLesson(l,t){return{id:String(l.id||uid()),createdAt:Number(l.createdAt||Date.now()),notes:String(l.notes||""),route:Array.isArray(l.route)?l.route.filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng)).map(p=>({...p,breakBefore:!!p.breakBefore})):[],checklist:normalizeItems(l.checklist,t)}}
function load(){try{const a=JSON.parse(localStorage.getItem(KEY)||"[]");return Array.isArray(a)?a.map(normalizeStudent):[]}catch{return []}}
function save(){state.students=state.students.map(normalizeStudent);localStorage.setItem(KEY,JSON.stringify(state.students))}
function show(id){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(id).classList.add("active");scrollTo(0,0)}
function student(){return state.students.find(s=>s.id===state.studentId)}function lesson(){return student()?.lessons.find(l=>l.id===state.lessonId)}
function nameOf(s){return[s.firstName,s.lastName].filter(Boolean).join(" ")}function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function stateIcon(v){return v==="repeat"?"🟡":v==="good"?"✅":"⬜"}function nextState(v){return STATES[(STATES.indexOf(v)+1)%STATES.length]}
function renderStateItems(items,box,onchange){box.innerHTML="";items.forEach((it,i)=>{const r=document.createElement("div");r.className="state-row";const b=document.createElement("button");b.type="button";b.className=`state-btn ${it.status}`;b.textContent=stateIcon(it.status);b.onclick=()=>{it.status=nextState(it.status);b.textContent=stateIcon(it.status);b.className=`state-btn ${it.status}`;onchange(i,it.status)};const s=document.createElement("span");s.textContent=it.label;r.append(b,s);box.appendChild(r)})}
function renderStudents(){const q=$("search").value.trim().toLowerCase(),a=state.students.filter(s=>state.filter==="all"||s.category===state.filter).filter(s=>(nameOf(s)+" "+s.phone+" "+s.license).toLowerCase().includes(q)).sort((a,b)=>nameOf(a).localeCompare(nameOf(b),"it"));$("students").innerHTML="";$("emptyStudents").classList.toggle("hidden",a.length>0);a.forEach(s=>{const b=document.createElement("button");b.className="student-card";b.innerHTML=`<strong>${esc(nameOf(s)||"Senza nome")}</strong><span class="meta">${LABELS[s.category]} · ${esc(s.license||"Patente non indicata")} · ${s.lessons.length} guide</span>`;b.onclick=()=>openStudent(s.id);$("students").appendChild(b)})}
function openStudent(id){state.studentId=id;const s=student();$("studentName").textContent=nameOf(s)||"Allievo";$("studentDetails").innerHTML=`<div class="detail-row"><span class="detail-label">Nome:</span> ${esc(s.firstName||"-")}</div><div class="detail-row"><span class="detail-label">Cognome:</span> ${esc(s.lastName||"-")}</div><div class="detail-row"><span class="detail-label">Categoria:</span> ${LABELS[s.category]}</div><div class="detail-row"><span class="detail-label">Telefono:</span> ${esc(s.phone||"-")}</div><div class="detail-row"><span class="detail-label">Patente:</span> ${esc(s.license||"-")}</div><div class="detail-row"><span class="detail-label">Note:</span> ${esc(s.notes||"-")}</div>`;$("checklistType").textContent=`Checklist ${LABELS[typeOf(s.category)]}`;renderStateItems(s.checklist,$("studentChecklist"),(i,v)=>{s.checklist[i].status=v;save()});renderLessons();show("student")}
function renderLessons(){const s=student();$("lessons").innerHTML="";$("emptyLessons").classList.toggle("hidden",s.lessons.length>0);[...s.lessons].sort((a,b)=>b.createdAt-a.createdAt).forEach(l=>{const b=document.createElement("button");b.className="lesson-card";const marked=l.checklist.filter(x=>x.status!=="none").length;b.innerHTML=`<strong>${new Date(l.createdAt).toLocaleString("it-IT")}</strong><span>${esc(l.notes||"Nessuna nota")}</span><span class="meta">${marked} voci segnate · ${l.route.length>1?"GPS presente":"GPS non usato"} · Tocca per aprire</span>`;b.onclick=()=>openLesson(l.id);$("lessons").appendChild(b)})}
function newStudent(){state.editingStudent=null;$("studentFormTitle").textContent="Nuovo allievo";$("category").value=state.filter||"auto";try{$("category").closest("label").style.display="none"}catch(e){}["firstName","lastName","phone","license","studentNotes"].forEach(id=>$(id).value="");try{$("category").closest("label").style.display=""}catch(e){}show("studentForm")}
function editStudent(){const s=student();state.editingStudent=s.id;$("studentFormTitle").textContent="Modifica allievo";$("category").value=s.category;$("firstName").value=s.firstName;$("lastName").value=s.lastName;$("phone").value=s.phone;$("license").value=s.license;$("studentNotes").value=s.notes;try{$("category").closest("label").style.display=""}catch(e){}show("studentForm")}
function saveStudent(){const c=$("category").value,first=$("firstName").value.trim(),last=$("lastName").value.trim();if(!first&&!last)return alert("Inserisci nome o cognome.");if(state.editingStudent){const s=state.students.find(x=>x.id===state.editingStudent),oldType=typeOf(s.category),newType=typeOf(c);Object.assign(s,{category:c,firstName:first,lastName:last,phone:$("phone").value.trim(),license:$("license").value.trim(),notes:$("studentNotes").value.trim()});if(oldType!==newType){s.checklist=normalizeItems([],newType);s.lessons=s.lessons.map(l=>({...l,checklist:normalizeItems([],newType)}))}save();openStudent(s.id)}else{const s=normalizeStudent({id:uid(),category:c,firstName:first,lastName:last,phone:$("phone").value.trim(),license:$("license").value.trim(),notes:$("studentNotes").value.trim(),checklist:[],lessons:[]});state.students.push(s);save();openStudent(s.id)}}
function deleteStudent(){const s=student();if(confirm(`Eliminare definitivamente ${nameOf(s)}?`)){state.students=state.students.filter(x=>x.id!==s.id);save();renderStudents();show("home")}}
function renderLessonChecklist(items){$("lessonChecklist").dataset.items=JSON.stringify(items);renderStateItems(items,$("lessonChecklist"),(i,v)=>{const a=JSON.parse($("lessonChecklist").dataset.items);a[i].status=v;$("lessonChecklist").dataset.items=JSON.stringify(a)})}
function newLesson(){state.lessonId=null;const now=new Date(),items=student().checklist.map(x=>({...x}));$("lessonTitle").textContent="Nuova guida";$("lessonDate").value=now.toISOString().slice(0,10);$("lessonTime").value=now.toTimeString().slice(0,5);$("lessonNotes").value="";$("deleteLesson").classList.add("hidden");$("openSavedRoute").classList.add("hidden");state.tempRoute=[];renderLessonChecklist(items);resetGps();show("lesson")}
function openLesson(id){state.lessonId=id;const l=lesson(),d=new Date(l.createdAt);$("lessonTitle").textContent="Modifica guida";$("lessonDate").value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;$("lessonTime").value=`${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`;$("lessonNotes").value=l.notes;$("deleteLesson").classList.remove("hidden");$("openSavedRoute").classList.toggle("hidden",l.route.length<2);state.tempRoute=[...l.route];renderLessonChecklist(l.checklist.map(x=>({...x})));resetGps();show("lesson")}
function saveLesson(){stopGps();const stamp=new Date(`${$("lessonDate").value}T${$("lessonTime").value||"00:00"}:00`).getTime(),data={createdAt:stamp,notes:$("lessonNotes").value.trim(),route:[...state.tempRoute],checklist:JSON.parse($("lessonChecklist").dataset.items||"[]")};if(state.lessonId)Object.assign(lesson(),data);else student().lessons.push({id:uid(),...data});save();openStudent(state.studentId)}
function deleteLesson(){if(confirm("Eliminare questa guida?")){student().lessons=student().lessons.filter(x=>x.id!==state.lessonId);save();openStudent(state.studentId)}}
function initLiveMap(){if(!state.liveMap){state.liveMap=L.map("liveMap").setView([44.4056,8.9463],13);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap"}).addTo(state.liveMap)}setTimeout(()=>state.liveMap.invalidateSize(),80)}
function routeSegments(route){const segments=[];let current=[];route.forEach((point,index)=>{if(index>0&&point.breakBefore&&current.length){segments.push(current);current=[]}current.push([point.lat,point.lng])});if(current.length)segments.push(current);return segments}
function drawLive(){initLiveMap();if(state.liveLine)state.liveMap.removeLayer(state.liveLine);if(state.liveMarker)state.liveMap.removeLayer(state.liveMarker);state.liveLine=null;state.liveMarker=null;if(!state.tempRoute.length)return;const segments=routeSegments(state.tempRoute),layers=segments.filter(x=>x.length>1).map(x=>L.polyline(x,{weight:5}));state.liveLine=L.featureGroup(layers).addTo(state.liveMap);const last=state.tempRoute.at(-1);state.liveMarker=L.marker([last.lat,last.lng]).addTo(state.liveMap);if(state.tempRoute.length===1)state.liveMap.setView([last.lat,last.lng],17);else{const bounds=state.liveLine.getBounds();if(bounds.isValid())state.liveMap.fitBounds(bounds,{padding:[20,20]});else state.liveMap.setView([last.lat,last.lng],17)}}
function startGps(){if(!navigator.geolocation||state.watch!==null)return;$("gpsStatus").textContent="GPS in acquisizione…";$("startGps").disabled=true;$("stopGps").disabled=false;state.watch=navigator.geolocation.watchPosition(pos=>{const p={lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:Number(pos.coords.accuracy||999),time:pos.timestamp,breakBefore:false};if(p.accuracy>70){$("gpsStatus").textContent="GPS attivo · attendo un segnale più preciso";return}const prev=state.tempRoute.at(-1);if(!prev){state.tempRoute.push(p);drawLive()}else{const metres=distance(prev,p),hasTime=Number.isFinite(prev.time),seconds=hasTime?Math.max(0.001,(p.time-prev.time)/1000):0,speed=hasTime?metres/seconds:0;if(metres>=5){p.breakBefore=!hasTime&&metres>80||hasTime&&seconds>15&&metres>80||metres>300||hasTime&&speed>55;state.tempRoute.push(p);drawLive()}}$("gpsStatus").textContent=`GPS attivo · ${state.tempRoute.length} punti`},err=>{$("gpsStatus").textContent=err.code===1?"Permesso GPS negato.":"Errore GPS.";stopGps()},{enableHighAccuracy:true,maximumAge:0,timeout:15000})}
function stopGps(){if(state.watch!==null)navigator.geolocation.clearWatch(state.watch);state.watch=null;$("startGps").disabled=false;$("stopGps").disabled=true}function resetGps(){stopGps();$("gpsStatus").textContent=state.tempRoute.length?`Percorso presente · ${state.tempRoute.length} punti`:"GPS non attivo.";drawLive()}
function distance(a,b){const R=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lng-a.lng)*Math.PI/180,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
function showSavedRoute(){const l=lesson();if(!l||l.route.length<2)return;show("savedMapView");if(!state.savedMap){state.savedMap=L.map("savedMap");L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"© OpenStreetMap"}).addTo(state.savedMap)}if(state.savedLine)state.savedMap.removeLayer(state.savedLine);const layers=routeSegments(l.route).filter(x=>x.length>1).map(x=>L.polyline(x,{weight:6}));state.savedLine=L.featureGroup(layers).addTo(state.savedMap);const bounds=state.savedLine.getBounds();if(bounds.isValid())state.savedMap.fitBounds(bounds,{padding:[20,20]});setTimeout(()=>state.savedMap.invalidateSize(),80)}
function syncLists(type){state.students.forEach(s=>{if(typeOf(s.category)!==type)return;s.checklist=normalizeItems(s.checklist,type);s.lessons=s.lessons.map(l=>({...l,checklist:normalizeItems(l.checklist,type)}))});saveLists();save()}
function renderChecklistManager(){document.querySelectorAll(".check-tabs button").forEach(b=>b.classList.toggle("active",b.dataset.list===state.managerType));const box=$("checklistManagerList");box.innerHTML="";LISTS[state.managerType].forEach((label,i)=>{const r=document.createElement("div");r.className="manager-row";r.innerHTML=`<div class="manager-label">${esc(label)}</div><div class="manager-actions"><button class="secondary up" ${i===0?"disabled":""}>↑</button><button class="secondary down" ${i===LISTS[state.managerType].length-1?"disabled":""}>↓</button><button class="secondary rename">Rinomina</button><button class="danger remove">Elimina</button></div>`;r.querySelector(".up").onclick=()=>moveChecklist(i,-1);r.querySelector(".down").onclick=()=>moveChecklist(i,1);r.querySelector(".rename").onclick=()=>renameChecklist(i);r.querySelector(".remove").onclick=()=>removeChecklist(i);box.appendChild(r)})}
function addChecklist(){const input=$("newChecklistLabel"),label=input.value.trim();if(!label)return;if(LISTS[state.managerType].some(x=>x.toLowerCase()===label.toLowerCase()))return alert("Questa voce esiste già.");LISTS[state.managerType].push(label);input.value="";syncLists(state.managerType);renderChecklistManager()}
function renameChecklist(i){const old=LISTS[state.managerType][i],next=prompt("Nuovo nome",old);if(next===null||!next.trim())return;LISTS[state.managerType][i]=next.trim();state.students.forEach(s=>{if(typeOf(s.category)!==state.managerType)return;(s.checklist||[]).forEach(x=>{if(x.label===old)x.label=next.trim()});(s.lessons||[]).forEach(l=>(l.checklist||[]).forEach(x=>{if(x.label===old)x.label=next.trim()}))});saveLists();save();renderChecklistManager()}
function removeChecklist(i){const label=LISTS[state.managerType][i];if(!confirm(`Eliminare "${label}" da tutte le schede?`))return;LISTS[state.managerType].splice(i,1);syncLists(state.managerType);renderChecklistManager()}function moveChecklist(i,d){const t=i+d;if(t<0||t>=LISTS[state.managerType].length)return;[LISTS[state.managerType][i],LISTS[state.managerType][t]]=[LISTS[state.managerType][t],LISTS[state.managerType][i]];syncLists(state.managerType);renderChecklistManager()}

function examinerName(x){return[x.firstName,x.lastName].filter(Boolean).join(" ")}
function renderExaminers(){const box=$("examinerList");box.innerHTML="";$("emptyExaminers").classList.toggle("hidden",state.examiners.length>0);[...state.examiners].sort((a,b)=>examinerName(a).localeCompare(examinerName(b),"it")).forEach(x=>{const b=document.createElement("button");b.className="student-card";b.innerHTML=`<strong>${esc(examinerName(x)||"Senza nome")}</strong><span class="meta">${x.habits.length} abitudini</span>`;b.onclick=()=>openExaminer(x.id);box.appendChild(b)})}
function renderHabits(){const box=$("habitList");box.innerHTML="";state.habitDraft.forEach((habit,index)=>{const row=document.createElement("div");row.className="manager-row";row.innerHTML=`<div class="manager-label">${esc(habit)}</div><div class="manager-actions"><button class="secondary rename-habit">Modifica</button><button class="danger remove-habit">Elimina</button></div>`;row.querySelector(".rename-habit").onclick=()=>{const next=prompt("Modifica abitudine",habit);if(next!==null&&next.trim()){state.habitDraft[index]=next.trim();renderHabits()}};row.querySelector(".remove-habit").onclick=()=>{state.habitDraft.splice(index,1);renderHabits()};box.appendChild(row)})}
function newExaminer(){state.examinerId=null;state.editingExaminer=null;state.habitDraft=[];$("examinerFormTitle").textContent="Nuovo esaminatore";$("examinerFirstName").value="";$("examinerLastName").value="";$("newHabit").value="";$("examinerNotes").value="";$("deleteExaminer").classList.add("hidden");renderHabits();show("examinerForm")}
function openExaminer(id){const x=state.examiners.find(e=>e.id===id);if(!x)return;state.examinerId=id;state.editingExaminer=id;state.habitDraft=[...x.habits];$("examinerFormTitle").textContent="Modifica esaminatore";$("examinerFirstName").value=x.firstName;$("examinerLastName").value=x.lastName;$("newHabit").value="";$("examinerNotes").value="";$("deleteExaminer").classList.remove("hidden");renderHabits();show("examinerForm")}
function addHabit(){const input=$("newHabit"),value=input.value.trim();if(!value)return;state.habitDraft.push(value);input.value="";renderHabits()}
function saveExaminer(){const firstName=$("examinerFirstName").value.trim(),lastName=$("examinerLastName").value.trim(),notes=$("examinerNotes").value;if(!firstName&&!lastName)return alert("Inserisci nome o cognome.");if(state.editingExaminer){const x=state.examiners.find(e=>e.id===state.editingExaminer);Object.assign(x,{firstName,lastName,notes,habits:[...state.habitDraft]})}else state.examiners.push({id:uid(),firstName,lastName,notes,habits:[...state.habitDraft]});saveExaminers();renderExaminers();show("examiners")}
function deleteExaminer(){if(!state.editingExaminer||!confirm("Eliminare questo esaminatore?"))return;state.examiners=state.examiners.filter(e=>e.id!==state.editingExaminer);saveExaminers();renderExaminers();show("examiners")}
function toggleVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert("Usa il microfono della tastiera del telefono.");if(!state.recognition){state.recognition=new SR();state.recognition.lang="it-IT";state.recognition.continuous=true;state.recognition.onresult=e=>{let t="";for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)t+=e.results[i][0].transcript+" ";(document.activeElement&&document.activeElement.id==="examinerNotes"?$("examinerNotes"):$("lessonNotes")).value+=t};state.recognition.onend=()=>{state.recognizing=false;$("voice").textContent="🎤 Detta"}}if(state.recognizing)state.recognition.stop();else{state.recognition.start();state.recognizing=true;$("voice").textContent="⏹ Ferma dettatura"}}
$("search").oninput=renderStudents;$("newStudent").onclick=newStudent;$("openExaminers").onclick=()=>{renderExaminers();show("examiners")};$("backExaminers").onclick=()=>{renderStudents();show("home")};$("newExaminer").onclick=newExaminer;$("backExaminerForm").onclick=()=>{renderExaminers();show("examiners")};$("saveExaminer").onclick=saveExaminer;$("deleteExaminer").onclick=deleteExaminer;$("addHabit").onclick=addHabit;$("newHabit").onkeydown=e=>{if(e.key==="Enter")addHabit()};document.querySelectorAll(".categories button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".categories button").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.filter=b.dataset.f;renderStudents()});$("backStudentForm").onclick=()=>state.editingStudent?openStudent(state.editingStudent):show("home");$("saveStudent").onclick=saveStudent;$("backHome").onclick=()=>{renderStudents();show("home")};$("editStudent").onclick=editStudent;$("deleteStudent").onclick=deleteStudent;$("newLesson").onclick=newLesson;$("backLesson").onclick=()=>{stopGps();openStudent(state.studentId)};$("saveLesson").onclick=saveLesson;$("deleteLesson").onclick=deleteLesson;$("startGps").onclick=startGps;$("stopGps").onclick=stopGps;$("voice").onclick=toggleVoice;$("openSavedRoute").onclick=showSavedRoute;$("backSavedMap").onclick=()=>show("lesson");$("manageChecklists").onclick=()=>{renderChecklistManager();show("checklistManager")};$("backChecklistManager").onclick=()=>{renderStudents();show("home")};document.querySelectorAll(".check-tabs button").forEach(b=>b.onclick=()=>{state.managerType=b.dataset.list;renderChecklistManager()});$("addChecklistItem").onclick=addChecklist;$("newChecklistLabel").onkeydown=e=>{if(e.key==="Enter")addChecklist()};
saveLists();save();if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").catch(()=>{}));renderStudents();

$("voiceExaminer")&&($("voiceExaminer").onclick=()=>{$("examinerNotes").focus();toggleVoice()});
