"use strict";
(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;if(root)root.DrivingErrors=api})(typeof window!=="undefined"?window:globalThis,function(){
const MAX_NOTE_LENGTH=500,FIX_MAX_AGE_MS=30000,DOUBLE_TAP_GUARD_MS=1000,DRAFT_PREFIX="agenda_driving_error_draft_v1";
const CATEGORIES=Object.freeze([{id:"precedence",label:"Precedenza"},{id:"signs",label:"Segnaletica"},{id:"speed",label:"Velocità"},{id:"positioning",label:"Posizionamento"},{id:"maneuver",label:"Manovra"},{id:"controls",label:"Uso comandi"},{id:"observation",label:"Osservazione"},{id:"other",label:"Altro"}].map(Object.freeze)),CATEGORY_IDS=new Set(CATEGORIES.map(item=>item.id));
const text=(value,max=Infinity)=>String(value??"").trim().slice(0,max),finite=value=>{const number=Number(value);return Number.isFinite(number)?number:null},identifier=(value,fallback="")=>text(value,160)||fallback,makeId=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}_${Math.random().toString(36).slice(2)}`;
function categoryLabel(value){return value==="unclassified"?"Da classificare":CATEGORIES.find(item=>item.id===value)?.label||"Da classificare"}
function normalizeError(raw,index=0){if(!raw||typeof raw!=="object")return null;const occurredAt=finite(raw.occurredAt)??finite(raw.createdAt)??Date.now(),createdAt=finite(raw.createdAt)??occurredAt,updatedAt=finite(raw.updatedAt)??createdAt,category=CATEGORY_IDS.has(raw.category)?raw.category:"unclassified",status=category==="unclassified"?"pending":raw.status==="pending"?"pending":"completed",locationStatus=["available","unavailable","low_accuracy","stale"].includes(raw.locationStatus)?raw.locationStatus:"unavailable",lat=finite(raw.lat),lng=finite(raw.lng),accuracy=finite(raw.accuracy),usableLocation=locationStatus==="available"&&lat!==null&&lng!==null&&accuracy!==null&&accuracy>=0&&accuracy<=100,result={id:identifier(raw.id,`error_${occurredAt}_${index}`),occurredAt,category,status,note:text(raw.note,MAX_NOTE_LENGTH),locationStatus:usableLocation?"available":locationStatus==="low_accuracy"?"low_accuracy":locationStatus==="stale"?"stale":"unavailable",gpsState:identifier(raw.gpsState,"inactive"),createdAt,updatedAt};if(usableLocation){result.lat=lat;result.lng=lng;result.accuracy=accuracy;const routeIndex=finite(raw.routeIndex),routePointTime=finite(raw.routePointTime);if(routeIndex!==null&&routeIndex>=0)result.routeIndex=Math.floor(routeIndex);if(routePointTime!==null)result.routePointTime=routePointTime}return result}
function normalizeErrors(items){if(!Array.isArray(items))return[];const seen=new Set();return items.map(normalizeError).filter(item=>item&&!seen.has(item.id)&&seen.add(item.id)).sort((a,b)=>a.occurredAt-b.occurredAt||a.createdAt-b.createdAt||a.id.localeCompare(b.id))}
function createError(options={}){const now=finite(options.now)??Date.now(),fix=options.lastAcceptedFix,observation=options.lastObservation,gpsState=identifier(options.gpsState,options.gpsActive?"active":"inactive"),base={id:identifier(options.id,makeId()),occurredAt:now,category:"unclassified",status:"pending",note:"",locationStatus:"unavailable",gpsState,createdAt:now,updatedAt:now},fixTime=finite(fix?.time),fixAge=fixTime===null?Infinity:now-fixTime;if(options.gpsActive&&fix&&finite(fix.lat)!==null&&finite(fix.lng)!==null&&finite(fix.accuracy)!==null&&fix.accuracy<=100&&fixAge>=0&&fixAge<=FIX_MAX_AGE_MS)return normalizeError({...base,locationStatus:"available",lat:fix.lat,lng:fix.lng,accuracy:fix.accuracy,routeIndex:fix.routeIndex,routePointTime:fix.time});const observationTime=finite(observation?.time),observationAge=observationTime===null?Infinity:now-observationTime;if(options.gpsActive&&observation&&finite(observation.accuracy)>100&&observationAge>=0&&observationAge<=FIX_MAX_AGE_MS)return normalizeError({...base,locationStatus:"low_accuracy"});if(options.gpsActive&&fix&&fixTime!==null&&fixAge>FIX_MAX_AGE_MS)return normalizeError({...base,locationStatus:"stale"});return normalizeError(base)}
const canSignal=(lastSignalAt,now=Date.now())=>!Number.isFinite(lastSignalAt)||now-lastSignalAt>=DOUBLE_TAP_GUARD_MS;
function draftKey(accountId,studentId,lessonContext){return`${DRAFT_PREFIX}:${[accountId,studentId,lessonContext].map(value=>encodeURIComponent(identifier(value,"missing"))).join(":")}`}
function createDraftStore(storage){if(!storage||typeof storage.getItem!=="function"||typeof storage.setItem!=="function"||typeof storage.removeItem!=="function")throw new TypeError("Storage locale non disponibile");return{load(accountId,studentId,lessonContext){try{const parsed=JSON.parse(storage.getItem(draftKey(accountId,studentId,lessonContext))||"null");if(!parsed||parsed.accountId!==String(accountId)||parsed.studentId!==String(studentId)||parsed.lessonContext!==String(lessonContext))return null;return{...parsed,errors:normalizeErrors(parsed.errors)}}catch{return null}},save(accountId,studentId,lessonContext,payload){const draft={version:1,accountId:String(accountId),studentId:String(studentId),lessonContext:String(lessonContext),draftLessonId:identifier(payload?.draftLessonId,makeId()),updatedAt:finite(payload?.updatedAt)??Date.now(),errors:normalizeErrors(payload?.errors)};storage.setItem(draftKey(accountId,studentId,lessonContext),JSON.stringify(draft));return draft},remove(accountId,studentId,lessonContext){storage.removeItem(draftKey(accountId,studentId,lessonContext))},key:draftKey}}
return{CATEGORIES,MAX_NOTE_LENGTH,FIX_MAX_AGE_MS,DOUBLE_TAP_GUARD_MS,categoryLabel,normalizeError,normalizeErrors,createError,canSignal,draftKey,createDraftStore};
});
