(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;if(root)root.AgendaExams=api})(typeof globalThis!=="undefined"?globalThis:this,function(){
"use strict";
const EXAMS_KEY="autoscuola_v3_exam_sessions",LOCATIONS_KEY="autoscuola_v3_exam_locations";
const DB_NAME="agenda_istruttori_exams",DB_VERSION=1,MIGRATION_KEY="localstorage-v1";
const DEFAULT_LOCATIONS=["Via delle Genziane","Via Bobbio","Villa Bombrini"];
const OUTCOMES=new Set(["","I","R","A"]),clone=value=>value==null?value:JSON.parse(JSON.stringify(value));
function clean(value){return String(value||"").trim().replace(/\s+/g," ")}
function validDate(value){return /^\d{4}-\d{2}-\d{2}$/.test(String(value||""))&&!Number.isNaN(new Date(`${value}T12:00:00`).getTime())}
function validTime(value){return /^(?:(?:[01]\d|2[0-3]):[0-5]\d|24:00)$/.test(String(value||""))}
function normalizeTimeInput(value,{optional=false}={}){const input=String(value??"").trim();if(!input&&optional)return"";let match=input.match(/^(\d{1,2})$/);if(match){const hour=Number(match[1]);if(hour<=24)return`${String(hour).padStart(2,"0")}:00`}match=input.match(/^(\d{1,2})[.:](\d{2})$/);if(!match)throw Error("Inserisci un orario valido, per esempio 13, 13.30 oppure 14:30.");const hour=Number(match[1]),minute=Number(match[2]);if(hour>24||minute>59||(hour===24&&minute!==0))throw Error("L’orario inserito non è valido. Usa ore da 0 a 24 (24:00 soltanto) e minuti da 00 a 59.");return`${String(hour).padStart(2,"0")}:${String(minute).padStart(2,"0")}`}
function normalizeParticipant(raw){const outcome=OUTCOMES.has(String(raw?.outcome||""))?String(raw?.outcome||""):"";return{studentId:clean(raw?.studentId),outcome,rejectionNote:clean(raw?.rejectionNote)}}
function normalizeExam(raw,{strict=false,idFactory=()=>crypto.randomUUID()}={}){
 const participants=Array.isArray(raw?.participants)?raw.participants.map(normalizeParticipant):[],seen=new Set;
 let startTime="",endTime="";try{startTime=normalizeTimeInput(raw?.startTime);endTime=normalizeTimeInput(raw?.endTime,{optional:true})}catch(error){if(strict)throw error;startTime=String(raw?.startTime||"");endTime=String(raw?.endTime||"")}
 if(strict&&(!raw||typeof raw!=="object"||!clean(raw.id)||!validDate(raw.date)||!validTime(startTime)||(endTime&&(!validTime(endTime)||endTime<=startTime))||!clean(raw.location)||!participants.length))throw Error(endTime&&endTime<=startTime?"L’ora di fine deve essere successiva all’ora di inizio.":"Sessione d’esame non valida.");
 for(const item of participants){if(!item.studentId||seen.has(item.studentId))throw Error("Partecipante duplicato o non valido nell’esame.");seen.add(item.studentId)}
 return{id:clean(raw?.id)||idFactory(),date:String(raw?.date||""),startTime,endTime,location:clean(raw?.location),examinerId:clean(raw?.examinerId),examinerName:clean(raw?.examinerName),instructorId:clean(raw?.instructorId),instructorName:clean(raw?.instructorName),participants,createdAt:Number(raw?.createdAt)||Date.now(),updatedAt:Number(raw?.updatedAt)||Date.now()};
}
function normalizeExams(raw,{strict=false,idFactory}={}){if(raw==null)return[];if(!Array.isArray(raw))throw Error("Archivio esami non valido.");const ids=new Set;return raw.map(item=>{const exam=normalizeExam(item,{strict,idFactory});if(ids.has(exam.id))throw Error("ID esame duplicato.");ids.add(exam.id);return exam})}
function normalizeLocations(raw){const values=Array.isArray(raw)&&raw.length?raw:DEFAULT_LOCATIONS,names=[],seenNames=new Set,seenIds=new Set;for(const value of values){const name=clean(typeof value==="string"?value:value?.name),key=name.toLocaleLowerCase("it-IT"),id=clean(value?.id)||`location-${key.replace(/[^a-z0-9]+/g,"-")}`;if(!name||seenNames.has(key)||seenIds.has(id))continue;seenNames.add(key);seenIds.add(id);names.push({id,name})}return names}
function canonicalArchive(exams,locations,{strict=true,idFactory}={}){const byId=(a,b)=>a.id.localeCompare(b.id,"it-IT");return{exams:normalizeExams(exams||[],{strict,idFactory}).slice().sort(byId),locations:normalizeLocations(locations||[]).slice().sort(byId)}}
function archivesEqual(leftExams,leftLocations,rightExams,rightLocations,options){return JSON.stringify(canonicalArchive(leftExams,leftLocations,options))===JSON.stringify(canonicalArchive(rightExams,rightLocations,options))}
function legacyValue(storage,key,fallback){const raw=storage?.getItem(key);if(raw===null||raw===undefined)return{status:"absent",value:clone(fallback)};if(raw==="")throw Error(`Archivio locale ${key} vuoto o illeggibile.`);let value;try{value=JSON.parse(raw)}catch{throw Error(`Archivio locale ${key} malformato. Nessun dato è stato modificato.`)}return{status:Array.isArray(value)&&value.length===0?"empty":"present",value}}
function requestResult(request){return new Promise((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||Error("IndexedDB non disponibile."))})}
function transactionDone(tx){return new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error||Error("Operazione IndexedDB non riuscita."));tx.onabort=()=>reject(tx.error||Error("Operazione IndexedDB annullata."))})}
function openDatabase(indexedDb,name=DB_NAME){return new Promise((resolve,reject)=>{if(!indexedDb?.open)return reject(Error("Archivio IndexedDB non disponibile su questo dispositivo."));const request=indexedDb.open(name,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains("exams"))db.createObjectStore("exams",{keyPath:"id"});if(!db.objectStoreNames.contains("locations"))db.createObjectStore("locations",{keyPath:"id"});if(!db.objectStoreNames.contains("meta"))db.createObjectStore("meta",{keyPath:"key"})};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error||Error("Impossibile aprire l’archivio esami."));request.onblocked=()=>reject(Error("Archivio esami occupato da un’altra finestra."))})}
function createIndexedDbBackend(indexedDb,{name=DB_NAME}={}){let dbPromise;const db=()=>dbPromise||(dbPromise=openDatabase(indexedDb,name));return{
 async getAll(store){const database=await db(),tx=database.transaction(store,"readonly");const value=await requestResult(tx.objectStore(store).getAll());await transactionDone(tx);return clone(value)},
 async get(store,key){const database=await db(),tx=database.transaction(store,"readonly");const value=await requestResult(tx.objectStore(store).get(key));await transactionDone(tx);return clone(value)},
 async put(store,value){const database=await db(),tx=database.transaction(store,"readwrite");tx.objectStore(store).put(clone(value));await transactionDone(tx)},
 async delete(store,key){const database=await db(),tx=database.transaction(store,"readwrite");tx.objectStore(store).delete(key);await transactionDone(tx)},
 async replaceAll(exams,locations,meta){const database=await db(),tx=database.transaction(["exams","locations","meta"],"readwrite"),examStore=tx.objectStore("exams"),locationStore=tx.objectStore("locations");examStore.clear();locationStore.clear();exams.forEach(item=>examStore.put(clone(item)));locations.forEach(item=>locationStore.put(clone(item)));if(meta)tx.objectStore("meta").put(clone(meta));await transactionDone(tx)},
 close:async()=>{const database=await db();database.close();dbPromise=null}
}}
function createMemoryBackend(options={}){const stores={exams:new Map,locations:new Map,meta:new Map};let failNext=options.failNext||null;const check=()=>{if(failNext){const error=failNext;failNext=null;throw error}};return{stores,setFailure(error){failNext=error},async getAll(name){check();return clone([...stores[name].values()])},async get(name,key){check();return clone(stores[name].get(key))},async put(name,value){check();stores[name].set(value.id??value.key,clone(value))},async delete(name,key){check();stores[name].delete(key)},async replaceAll(exams,locations,meta){check();const next={exams:new Map(exams.map(x=>[x.id,clone(x)])),locations:new Map(locations.map(x=>[x.id,clone(x)])),meta:new Map(stores.meta)};if(meta)next.meta.set(meta.key,clone(meta));stores.exams=next.exams;stores.locations=next.locations;stores.meta=next.meta},async close(){}}}
function friendlyStorageError(error){if(error?.name==="QuotaExceededError")return Error("Spazio locale insufficiente: l’esame non è stato salvato. I dati precedenti sono rimasti invariati.");return Error(error?.message||"Archivio esami non disponibile. Nessun dato è stato modificato.")}
function createStore(options={}){if(options&&typeof options.getItem==="function")options={legacyStorage:options,backend:createMemoryBackend()};const legacyStorage=options.legacyStorage??(typeof localStorage!=="undefined"?localStorage:null),idFactory=options.idFactory||(()=>crypto.randomUUID()),backend=options.backend||createIndexedDbBackend(options.indexedDB??globalThis.indexedDB,options);let ready=false,queue=Promise.resolve();const serialized=task=>{const result=queue.then(task,task);queue=result.catch(()=>{});return result};
 async function initialize(){if(ready)return snapshot();return serialized(async()=>{if(ready)return snapshot();try{const migrated=await backend.get("meta",MIGRATION_KEY);if(!migrated){const oldExams=legacyValue(legacyStorage,EXAMS_KEY,[]),oldLocations=legacyValue(legacyStorage,LOCATIONS_KEY,[]),exams=normalizeExams(oldExams.value,{strict:true,idFactory}),locations=normalizeLocations(oldLocations.value);const meta={key:MIGRATION_KEY,status:"verified",source:{exams:oldExams.status,locations:oldLocations.status},count:{exams:exams.length,locations:locations.length},completedAt:Date.now()};await backend.replaceAll(exams,locations,meta);const verifyExams=await backend.getAll("exams"),verifyLocations=await backend.getAll("locations");if(!archivesEqual(verifyExams,verifyLocations,exams,locations,{strict:true,idFactory}))throw Error("Verifica della migrazione esami non riuscita.")}ready=true;return snapshot()}catch(error){ready=false;throw friendlyStorageError(error)}})}
 function requireReady(){if(!ready)throw Error("Archivio esami non inizializzato. Riprova ad aprire la sezione ESAMI.")}
 async function exams(){requireReady();try{return normalizeExams(await backend.getAll("exams"),{strict:true,idFactory})}catch(error){throw friendlyStorageError(error)}}
 async function locations(){requireReady();try{return normalizeLocations(await backend.getAll("locations"))}catch(error){throw friendlyStorageError(error)}}
 async function snapshot(){requireReady();return{exams:await exams(),locations:await locations()}}
 async function saveExam(raw){return serialized(async()=>{requireReady();const exam=normalizeExam(raw,{strict:true,idFactory});try{await backend.put("exams",exam);return clone(exam)}catch(error){throw friendlyStorageError(error)}})}
 async function deleteExam(id){return serialized(async()=>{requireReady();const exists=await backend.get("exams",id);if(!exists)return false;try{await backend.delete("exams",id);return true}catch(error){throw friendlyStorageError(error)}})}
 async function saveLocation(raw){return serialized(async()=>{requireReady();const name=clean(raw?.name??raw);if(!name)throw Error("Inserisci la località.");const current=await locations(),requestedId=clean(raw?.id),duplicate=current.find(item=>item.name.toLocaleLowerCase("it-IT")===name.toLocaleLowerCase("it-IT")&&item.id!==requestedId);if(duplicate)throw Error("Località già presente.");const item={id:requestedId||idFactory(),name};try{await backend.put("locations",item);return clone(item)}catch(error){throw friendlyStorageError(error)}})}
 async function replaceAll(nextExams,nextLocations){return serialized(async()=>{requireReady();const normalized=normalizeExams(nextExams||[],{strict:true,idFactory}),locationsNormalized=normalizeLocations(nextLocations||[]),before=await snapshot();try{await backend.replaceAll(normalized,locationsNormalized);const after=await snapshot();if(!archivesEqual(after.exams,after.locations,normalized,locationsNormalized,{strict:true,idFactory}))throw Error("Verifica archivio esami non riuscita.");return after}catch(error){try{await backend.replaceAll(before.exams,before.locations)}catch{}throw friendlyStorageError(error)}})}
 return Object.freeze({initialize,exams,locations,snapshot,saveExam,deleteExam,saveLocation,replaceAll,close:()=>backend.close(),migrationStatus:()=>backend.get("meta",MIGRATION_KEY)})}
function forStudents(exams,studentIds){const wanted=new Set(studentIds.map(String));return normalizeExams(exams||[],{strict:true}).map(exam=>({...exam,participants:exam.participants.filter(item=>wanted.has(item.studentId))})).filter(exam=>exam.participants.length)}
function outcomeLabel(value){return value==="I"?"Idoneo":value==="R"?"Respinto":value==="A"?"Assente":"Esito non inserito"}
 return Object.freeze({EXAMS_KEY,LOCATIONS_KEY,DB_NAME,DEFAULT_LOCATIONS,normalizeTimeInput,normalizeExam,normalizeExams,normalizeLocations,canonicalArchive,archivesEqual,createStore,createMemoryBackend,createIndexedDbBackend,forStudents,outcomeLabel,validDate,validTime});
});
