"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm"),root=path.join(__dirname,".."),read=file=>fs.readFileSync(path.join(root,file),"utf8");
const E=require("../exams.js"),L=require("../student-license.js"),D=require("../lesson-drafts.js"),S=require("../student-archive-store.js"),R=require("../examiner-routes.js"),M=require("../student-multi-import.js");
const exam={id:"e",date:"2026-09-20",startTime:"13",endTime:"",location:"SEDE FITTIZIA",participants:[{studentId:"s",outcome:"I"}],createdAt:1,updatedAt:1,instructorId:"i",instructorName:"ISTRUTTORE STORICO"};
test("istruttore storico resta in normalizzazione, canonica e trasferimento per ogni esito",()=>{for(const outcome of ["I","R","A",""]){const input={...exam,participants:[{studentId:"s",outcome,rejectionNote:"MOTIVO"}]},normalized=E.normalizeExam(input,{strict:true});assert.equal(normalized.instructorName,"ISTRUTTORE STORICO");assert.equal(E.forStudents([input],["s"])[0].instructorId,"i");assert.equal(E.archivesEqual([input],[],[{...input,instructorName:"ALTRO"}],[]),false)}const legacy={...exam};delete legacy.instructorId;delete legacy.instructorName;assert.equal(E.normalizeExam(legacy,{strict:true}).instructorName,"")});
test("orari fino a 24:00, separatori storici, virgola rifiutata e fine strettamente successiva",()=>{for(const input of ["24","24.00","24:00"])assert.equal(E.normalizeTimeInput(input),"24:00");for(const input of ["24:01","25","13,30","14:90"])assert.throws(()=>E.normalizeTimeInput(input),/orario|orari/);assert.equal(E.normalizeExam({...exam,startTime:"23:30",endTime:"24"},{strict:true}).endTime,"24:00");assert.throws(()=>E.normalizeExam({...exam,endTime:"13"},{strict:true}),/successiva/)});
test("categoria patente obbligatoria per nuovo salvataggio ma non inventata nello storico",()=>{const old={number:"TEST123",issueDate:"2026-01-01",expiryDate:"2036-01-01"};assert.deepEqual(L.normalize(old,{strict:true}),old);assert.throws(()=>L.normalize(old,{requireCategory:true}),/categoria/);assert.equal(L.normalize({...old,category:"be"},{requireCategory:true}).category,"BE");assert.throws(()=>L.normalize({...old,category:"Auto"},{requireCategory:true}),/Categoria/)});
test("catalogo sedi conserva fotografia allievo e sopravvive al riavvio",async()=>{const backend=S.createMemoryBackend(),store=S.createStore({backend,legacyStorage:{getItem:()=>JSON.stringify([{id:"s",siteId:"q",siteName:"SEDE STORICA"}])}});await store.initialize();assert.equal((await store.snapshotSites()).length,7);await store.replaceSites([{id:"q",name:"NOME NUOVO"}]);assert.equal((await store.snapshot())[0].siteName,"SEDE STORICA");await store.replaceSites([]);assert.equal((await store.snapshot())[0].siteId,"q");await assert.rejects(store.replaceSites([{id:"a",name:"Uno"},{id:"b",name:" uno "}]),/duplicata/);const reopened=S.createStore({backend,legacyStorage:{getItem(){throw Error()}}});await reopened.initialize();assert.deepEqual(await reopened.snapshotSites(),[])});
test("bozza GPS sopravvive a background e ricaricamento senza azzerare note punti errori e identità",async()=>{const backend=D.memoryBackend(),first=D.createStore({backend}),draft={id:"draft",accountId:"account-a",studentId:"s",lessonId:null,startedAt:1000,notes:"NOTA FITTIZIA",errors:[{id:"err"}],route:[{lat:44,lng:8,time:1000},{lat:44.001,lng:8.001,time:2000}],gpsNeedsBreak:true};await first.save(draft);const second=D.createStore({backend}),loaded=await second.load("account-a","s",null);assert.equal(loaded.notes,draft.notes);assert.deepEqual(loaded.route,draft.route);assert.deepEqual(loaded.errors,draft.errors);assert.equal(D.elapsed(loaded,61000),60000);assert.equal(await second.load("account-b","s",null),undefined);await second.save({...loaded,route:[...loaded.route,{lat:44.002,lng:8.002,time:61000,breakBefore:true}]});assert.equal((await second.load("account-a","s",null)).route.length,3)});
test("pausa GPS rompe sempre la linea al nuovo punto e conserva i punti precedenti",()=>{const source=read("app.js"),names=["distance","bearing","bearingDelta","evaluateGpsPoint"],code=names.map(name=>source.match(new RegExp(`function ${name}\\([^\\n]+`))[0]).join("\n"),context={};vm.runInNewContext(code+';globalThis.check=evaluateGpsPoint',context);const before={lat:44,lng:8,accuracy:5,time:1000},after={lat:44.0001,lng:8,accuracy:5,time:12000};assert.equal(context.check(before,after,true).breakBefore,true);assert.equal(context.check(before,{...after,time:999},true).accept,false);assert.deepEqual(before,{lat:44,lng:8,accuracy:5,time:1000})});
test("zona e titolo percorso restano compatibili con esportazione e record storici",()=>{const route=R.normalizeRoute({id:"r",examinerId:"e",title:"TITOLO",zone:"GENOVA DEMO",points:[]});assert.equal(route.zone,"GENOVA DEMO");assert.equal(R.normalizeRoute(JSON.parse(JSON.stringify(route))).zone,"GENOVA DEMO");assert.equal(R.normalizeRoute({id:"old",points:[]}).zone,"")});
test("nessun ID HTML duplicato e nessuna scrittura della sorgente archivio principale",()=>{const ids=[...read("index.html").matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);assert.equal(new Set(ids).size,ids.length);assert.doesNotMatch(read("app.js"),/localStorage\.setItem\(KEY,/);assert.doesNotMatch(read("full-backup.js"),/localStorage\.setItem\(DATA_KEYS.students,/)});

test("trasferimenti conservano sede, patente e istruttore anche nella copia e nel secondo import",async()=>{
 const pupil={id:"s",firstName:"DEMO",lastName:"TEST",siteId:"site",siteName:"SEDE STORICA",lessons:[],checklist:[],drivingLicense:{category:"BE",number:"TEST123",issueDate:"2026-01-01",expiryDate:"2036-01-01"}};
 const envelope=await M.validate({app:"Agenda Istruttore",version:"1.21",type:"students",students:[pupil],documents:[],exams:[E.normalizeExam(exam,{strict:true})]});
 let serial=0;const id=()=>"copy-"+(++serial),first=M.plan([],envelope,{},id),second=M.plan(first.students,envelope,{},id,first.exams),copy=M.plan(first.students,envelope,{s:"copy"},id,first.exams);
 assert.equal(second.counts.skipped,1);assert.equal(second.students.length,1);assert.equal(copy.students.length,2);
 const cloned=copy.students.find(s=>s.id!=="s");assert.equal(cloned.siteName,pupil.siteName);assert.equal(cloned.drivingLicense.category,"BE");assert.equal(copy.exams.find(e=>e.id!=="e").participants[0].studentId,cloned.id);assert.equal(copy.exams[1].instructorName,exam.instructorName);
});

test("ripristino sintetico nello store principale: formati storici, sedi e compensazione completa",async()=>{
 const clone=x=>JSON.parse(JSON.stringify(x)),backend=S.createMemoryBackend(),store=S.createStore({backend,legacyStorage:{getItem:()=>JSON.stringify([{id:"before",lessons:[],checklist:[]}])}});await store.initialize();
 let exams={exams:[],locations:[]},licenses=[],fail=false;const values=new Map([['source','FONTE INALTERATA'],['checks','{}'],['examiners','[]']]);
 const context={window:{AgendaExams:E,AgendaStudentArchiveStore:store,AgendaExamStore:{snapshot:async()=>clone(exams),replaceAll:async(e,l)=>{exams=clone({exams:e,locations:l})}},AgendaStudentLicenseStore:{snapshot:async()=>clone(licenses),replaceAll:async next=>{if(fail){fail=false;throw Error("quota simulata")}licenses=clone(next)}}},localStorage:{setItem:(k,v)=>values.set(k,v)},DATA_KEYS:{checklists:"checks",examiners:"examiners"},parsedStorageValue:(k,d)=>values.has(k)?JSON.parse(values.get(k)):d,studentsWithoutDrivingLicenses:rows=>rows.map(s=>{const r=clone(s);delete r.drivingLicense;return r}),drivingLicenseRecords:rows=>rows.filter(s=>s.drivingLicense).map(s=>({studentId:s.id,...s.drivingLicense}))};
 const fn=read("full-backup.js").match(/async function writeAppData\(appData\)\{[\s\S]*?\n  \}/)[0];vm.runInNewContext(fn+';globalThis.write=writeAppData',context);
 for(const version of [1,2,3,4]){const data={students:[{id:"synthetic-"+version,lessons:[],checklist:[]}],checklists:{auto:["TEST"]},examiners:[]};await context.write(data);assert.equal((await store.snapshot())[0].id,data.students[0].id);assert.deepEqual(exams,E.canonicalArchive([],[],{strict:true}))}
 const modern={students:[{id:"s",lessons:[],checklist:[],siteId:"site",siteName:"STORICA",drivingLicense:{category:"B",number:"TEST",issueDate:"2026-01-01",expiryDate:"2036-01-01"}}],studentSites:[{id:"site",name:"CATALOGO"}],exams:[exam],examLocations:[],checklists:{auto:[]},examiners:[]};await context.write(modern);
 const before={students:await store.snapshot(),sites:await store.snapshotSites(),exams:clone(exams),licenses:clone(licenses),values:[...values]};fail=true;await assert.rejects(context.write({...modern,students:[{id:"other"}],studentSites:[],exams:[]}),/quota simulata/);
 assert.deepEqual(await store.snapshot(),before.students);assert.deepEqual(await store.snapshotSites(),before.sites);assert.deepEqual(exams,before.exams);assert.deepEqual(licenses,before.licenses);assert.deepEqual([...values],before.values);await context.write(modern);assert.equal(values.get("source"),"FONTE INALTERATA");assert.equal(exams.exams[0].instructorId,"i");
});

test("normalizzazione checklist mantiene ID, ordine operativo e campi storici",()=>{const code=read("app.js"),context={LISTS:{auto:["B","A"]},uid:()=>"generated",oldStatus:x=>x.status||"none"};vm.runInNewContext(code.match(/function normalizeItems\([^\n]+/)[0]+';globalThis.normalize=normalizeItems',context);const input=[{id:"a",label:"A",status:"good",extra:42},{id:"b",label:"B",status:"repeat"}];assert.equal(JSON.stringify(context.normalize(input,"auto")),JSON.stringify(input))});

test("lifecycle guida: background pagehide freeze persistono senza azzerare la sessione",()=>{
 const handlers={},saved=[],source=read("app.js"),context={lessonDraftReady:true,state:{tempRoute:[{lat:44,lng:8}],tempErrors:[{id:"error"}],gpsNeedsBreak:false,gpsState:"active"},persistLessonSession(){saved.push(JSON.stringify(context.state))},stopGps(message,preserve){assert.equal(preserve,true)},updateGpsUi(){},document:{hidden:true,addEventListener:(name,fn)=>handlers[name]=fn},window:{addEventListener:(name,fn)=>handlers[name]=fn}};
 const code=source.match(/function suspendLessonSession\([^\n]+/)[0]+"\n"+source.split(/\r?\n/).filter(line=>/^(document|window)\.addEventListener\("(visibilitychange|pagehide|freeze|resume|pageshow)"/.test(line)).join("\n");vm.runInNewContext(code,context);
 for(const event of ["visibilitychange","pagehide","freeze","resume","pageshow"])handlers[event]();assert.equal(saved.length,3);assert.equal(context.state.gpsState,"suspended");assert.equal(context.state.gpsNeedsBreak,true);assert.equal(context.state.tempRoute.length,1);assert.equal(context.state.tempErrors[0].id,"error");
});
