"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),api=require("../driving-errors.js");
function memoryStorage(){const values=new Map();return{getItem:key=>values.has(key)?values.get(key):null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key),values}}
test("schema e normalizzazione retrocompatibile sono idempotenti",()=>{assert.deepEqual(api.normalizeErrors(undefined),[]);const input={id:"e1",occurredAt:1000,category:"precedence",status:"completed",note:"x".repeat(700),locationStatus:"available",lat:44,lng:8,accuracy:10,routeIndex:2,routePointTime:900,createdAt:1000,updatedAt:1100,gpsState:"active"},once=api.normalizeErrors([input]);assert.deepEqual(api.normalizeErrors(once),once);assert.equal(once[0].note.length,500);assert.equal(api.categoryLabel("unclassified"),"Da classificare")});
test("coordinate non finite non eliminano l'evento",()=>{const[event]=api.normalizeErrors([{id:"x",occurredAt:10,lat:NaN,lng:8,accuracy:5,locationStatus:"available"}]);assert.equal(event.locationStatus,"unavailable");assert.equal("lat" in event,false);assert.equal(event.category,"unclassified");assert.equal(event.status,"pending")});
test("segnalazione usa solo un fix accettato e recente",()=>{const event=api.createError({id:"e",now:31000,gpsActive:true,lastAcceptedFix:{lat:44,lng:8,accuracy:12,time:1001,routeIndex:3}});assert.equal(event.locationStatus,"available");assert.equal(event.routeIndex,3);const stale=api.createError({now:40001,gpsActive:true,lastAcceptedFix:{lat:44,lng:8,accuracy:12,time:10000,routeIndex:3}});assert.equal(stale.locationStatus,"stale");assert.equal("lat" in stale,false)});
test("precisione oltre 100 metri resta segnalata senza coordinate",()=>{const event=api.createError({now:5000,gpsActive:true,lastObservation:{lat:44,lng:8,accuracy:140,time:4500}});assert.equal(event.locationStatus,"low_accuracy");assert.equal("lat" in event,false)});
test("ordine cronologico e numerazione dopo eliminazione sono deterministici",()=>{const items=api.normalizeErrors([{id:"b",occurredAt:20},{id:"a",occurredAt:10},{id:"c",occurredAt:30}]);assert.deepEqual(items.map(x=>x.id),["a","b","c"]);items.splice(1,1);assert.deepEqual(items.map((x,i)=>[i+1,x.id]),[[1,"a"],[2,"c"]])});
test("protezione doppio tocco dura un secondo",()=>{assert.equal(api.canSignal(1000,1999),false);assert.equal(api.canSignal(1000,2000),true);assert.equal(api.canSignal(null,1000),true)});
test("bozze sono separate per account, allievo e guida",()=>{const storage=memoryStorage(),drafts=api.createDraftStore(storage),error=api.createError({id:"e",now:1});drafts.save("account-a","student-a","new",{draftLessonId:"draft-a",errors:[error]});assert.equal(drafts.load("account-a","student-a","new").errors.length,1);assert.equal(drafts.load("account-b","student-a","new"),null);assert.equal(drafts.load("account-a","student-b","new"),null);assert.equal(drafts.load("account-a","student-a","lesson-2"),null);drafts.remove("account-a","student-a","new");assert.equal(drafts.load("account-a","student-a","new"),null)});
test("modulo errori non usa rete né storage di sessione",()=>{const source=fs.readFileSync(path.join(__dirname,"..","driving-errors.js"),"utf8");assert.doesNotMatch(source,/\bfetch\s*\(|XMLHttpRequest|WebSocket|sessionStorage|indexedDB|\bD1\b/i)});
test("classificazione e modifica nota mantengono identità e cronologia",()=>{const original=api.createError({id:"e1",now:100}),classified=api.normalizeError({...original,category:"maneuver",status:"completed",note:"  Controllare lo specchietto  ",updatedAt:200});assert.equal(classified.id,"e1");assert.equal(classified.occurredAt,100);assert.equal(classified.category,"maneuver");assert.equal(classified.status,"completed");assert.equal(classified.note,"Controllare lo specchietto");assert.equal(classified.updatedAt,200)});
test("categoria sconosciuta torna in stato da classificare",()=>{const item=api.normalizeError({id:"e1",occurredAt:1,category:"<script>",status:"completed",note:"nota"});assert.equal(item.category,"unclassified");assert.equal(item.status,"pending")});
test("assenza GPS, permesso negato e fix oltre trenta secondi non producono coordinate",()=>{const withoutGps=api.createError({now:100,gpsActive:false,gpsState:"inactive"}),denied=api.createError({now:100,gpsActive:false,gpsState:"permission_denied"}),stale=api.createError({now:31001,gpsActive:true,lastAcceptedFix:{lat:44,lng:8,accuracy:5,time:1000}});for(const item of [withoutGps,denied,stale])assert.equal("lat" in item,false);assert.equal(denied.gpsState,"permission_denied");assert.equal(stale.locationStatus,"stale")});
test("più errori ravvicinati ma oltre la guardia restano distinti",()=>{const first=api.createError({id:"a",now:1000}),second=api.createError({id:"b",now:2001}),items=api.normalizeErrors([second,first]);assert.deepEqual(items.map(item=>item.id),["a","b"])});
test("bozza ripristinata conserva classificazione, note e ordine esatto",()=>{const storage=memoryStorage(),drafts=api.createDraftStore(storage),items=[api.normalizeError({id:"b",occurredAt:20,category:"speed",status:"completed",note:"Secondo"}),api.normalizeError({id:"a",occurredAt:10,note:"Primo"})];drafts.save("account","student","lesson",{draftLessonId:"lesson",errors:items});const restored=drafts.load("account","student","lesson");assert.deepEqual(restored.errors.map(item=>[item.id,item.category,item.note]),[["a","unclassified","Primo"],["b","speed","Secondo"]])});
