const test=require("node:test"),assert=require("node:assert/strict"),exams=require("C:/agenda_zena/Agenda-Istruttori-v1-21-LAVORO/exams.js"),multi=require("C:/agenda_zena/Agenda-Istruttori-v1-21-LAVORO/student-multi-import.js");
function memory(initial={}){const map=new Map(Object.entries(initial)),writes=[];return{map,writes,getItem:key=>map.has(key)?map.get(key):null,setItem:(key,value)=>{writes.push(key);map.set(key,String(value))}}}
const sample=(overrides={})=>({id:"exam-1",date:"2026-09-14",startTime:"09:00",endTime:"11:00",location:"Via Bobbio",participants:[{studentId:"s1",outcome:"",rejectionNote:""}],createdAt:1,updatedAt:1,...overrides});
async function store(initial={},backend=exams.createMemoryBackend()){const legacy=memory(initial),value=exams.createStore({legacyStorage:legacy,backend,idFactory:()=>"generated"});await value.initialize();return{store:value,legacy,backend}}
test("migrazione riuscita conserva le chiavi legacy e verifica conteggi",async()=>{const old=[sample()],legacy=memory({[exams.EXAMS_KEY]:JSON.stringify(old),[exams.LOCATIONS_KEY]:JSON.stringify([{id:"l1",name:"Via Test"}])}),backend=exams.createMemoryBackend(),vault=exams.createStore({legacyStorage:legacy,backend});const data=await vault.initialize(),meta=await vault.migrationStatus();assert.deepEqual(data.exams,old);assert.equal(data.locations[0].name,"Via Test");assert.equal(meta.status,"verified");assert.equal(meta.count.exams,1);assert.equal(legacy.writes.length,0);assert.equal(legacy.getItem(exams.EXAMS_KEY),JSON.stringify(old))});
test("migrazione interrotta riprende senza duplicare e quella ripetuta ignora il legacy",async()=>{const legacy=memory({[exams.EXAMS_KEY]:JSON.stringify([sample()])}),backend=exams.createMemoryBackend(),vault=exams.createStore({legacyStorage:legacy,backend});backend.setFailure(Object.assign(Error("interruzione"),{name:"AbortError"}));await assert.rejects(()=>vault.initialize(),/interruzione/);assert.equal((await backend.getAll("exams")).length,0);await vault.initialize();legacy.map.set(exams.EXAMS_KEY,"{corrotto dopo migrazione");const again=await vault.initialize();assert.equal(again.exams.length,1)});
test("archivio assente e vuoto sono validi ma malformato o corrotto bloccano",async()=>{assert.equal((await store()).store&&(await (await store()).store.exams()).length,0);const empty=await store({[exams.EXAMS_KEY]:"[]",[exams.LOCATIONS_KEY]:"[]"});assert.equal((await empty.store.exams()).length,0);for(const value of ["{",JSON.stringify([{id:"x"}])]){const vault=exams.createStore({legacyStorage:memory({[exams.EXAMS_KEY]:value}),backend:exams.createMemoryBackend()});await assert.rejects(()=>vault.initialize(),/malformato|non valida|orario valido/);await assert.rejects(()=>vault.saveExam(sample()),/non inizializzato/)}});
test("IndexedDB assente e quota insufficiente mostrano messaggi italiani e consentono nuovo tentativo",async()=>{const absent=exams.createStore({legacyStorage:memory(),indexedDB:null});await assert.rejects(()=>absent.initialize(),/IndexedDB non disponibile/);const setup=await store(),quota=Object.assign(Error("quota"),{name:"QuotaExceededError"});setup.backend.setFailure(quota);await assert.rejects(()=>setup.store.saveExam(sample()),/Spazio locale insufficiente/);assert.equal((await setup.store.exams()).length,0);await setup.store.saveExam(sample());assert.equal((await setup.store.exams()).length,1)});
test("salvataggi concorrenti sono serializzati e non riscrivono localStorage",async()=>{const setup=await store();await Promise.all([setup.store.saveExam(sample({id:"a"})),setup.store.saveExam(sample({id:"b"}))]);assert.deepEqual((await setup.store.exams()).map(x=>x.id).sort(),["a","b"]);assert.equal(setup.legacy.writes.length,0)});
test("crea e modifica per record conservando località storica",async()=>{const setup=await store(),saved=await setup.store.saveExam(sample());await setup.store.saveLocation({id:"loc",name:"Via Storica"});await setup.store.saveLocation({id:"loc",name:"Via Nuova"});assert.equal((await setup.store.exams())[0].location,"Via Bobbio");await setup.store.saveExam({...saved,endTime:"12:00"});assert.equal((await setup.store.exams())[0].endTime,"12:00")});
test("normalizza tutti i formati orari ammessi",()=>{for(const [input,expected] of [["13","13:00"],["13.30","13:30"],["14:30","14:30"],["9.05","09:05"],["0","00:00"]])assert.equal(exams.normalizeTimeInput(input),expected)});
test("rifiuta orari ambigui e impossibili con messaggio italiano",()=>{for(const value of ["25","13.5","13.75","14:90","13:","abc"])assert.throws(()=>exams.normalizeTimeInput(value),/orario|ore/)});
test("ora finale facoltativa può essere aggiunta dopo e deve essere successiva",()=>{const draft=exams.normalizeExam(sample({startTime:"13",endTime:""}),{strict:true});assert.equal(draft.startTime,"13:00");assert.equal(draft.endTime,"");assert.equal(exams.normalizeExam({...draft,endTime:"15.30"},{strict:true}).endTime,"15:30");assert.throws(()=>exams.normalizeExam({...draft,endTime:"13:00"},{strict:true}),/successiva/);assert.throws(()=>exams.normalizeExam({...draft,endTime:"12:59"},{strict:true}),/successiva/)});
test("valida data e impedisce partecipanti duplicati",()=>{assert.throws(()=>exams.normalizeExam(sample({date:"14/09/2026"}),{strict:true}),/non valida/);assert.throws(()=>exams.normalizeExam(sample({participants:[{studentId:"s1"},{studentId:"s1"}]}),{strict:true}),/duplicato/)});
test("esito iniziale vuoto, opzioni esclusive e nota preservata",()=>{const normalized=exams.normalizeExam(sample({participants:[{studentId:"s1",outcome:"R",rejectionNote:"Nota lunga ".repeat(80)}]}),{strict:true});assert.equal(normalized.participants[0].outcome,"R");assert.match(normalized.participants[0].rejectionNote,/Nota lunga/);assert.equal(exams.outcomeLabel(""),"Esito non inserito")});
test("filtra trasferimenti senza esporre altri partecipanti",()=>{const filtered=exams.forStudents([sample({participants:[{studentId:"s1",outcome:"I"},{studentId:"s2",outcome:"R",rejectionNote:"privata"}]})],["s1"]);assert.deepEqual(filtered[0].participants,[{studentId:"s1",outcome:"I",rejectionNote:""}])});
test("import multiplo rimappa copie e conserva compatibilità senza esami",async()=>{const envelope=await multi.validate({app:"Agenda Istruttore",version:"1.21.0",type:"students",students:[{id:"s1",lessons:[],checklist:[]}],exams:[sample({endTime:""})],documents:[]});let n=0;const copied=multi.plan([{id:"s1"}],envelope,{s1:"copy"},prefix=>`${prefix}-${++n}`,[sample()]);assert.notEqual(copied.students[1].id,"s1");assert.equal(copied.exams.length,2);const old=await multi.validate({app:"Agenda Istruttore",version:"1.21.0",type:"students",students:[{id:"old",lessons:[],checklist:[]}]});assert.deepEqual(old.exams,[])});
test("replaceAll è atomico e mantiene lo stato precedente se fallisce",async()=>{const setup=await store();await setup.store.saveExam(sample());setup.backend.setFailure(Object.assign(Error("quota"),{name:"QuotaExceededError"}));await assert.rejects(()=>setup.store.replaceAll([sample({id:"new"})],[]),/Spazio locale insufficiente/);assert.deepEqual((await setup.store.exams()).map(x=>x.id),["exam-1"])});
test("verifica canonica accetta rilettura IndexedDB ordinata per chiave senza mutare input",async()=>{const inner=exams.createMemoryBackend(),backend={...inner,getAll:async name=>(await inner.getAll(name)).sort((a,b)=>String(a.id??a.key).localeCompare(String(b.id??b.key)))},legacyExams=[sample({id:"z",endTime:undefined,participants:[{studentId:"s2",outcome:"A"},{studentId:"s1",outcome:"I"}]}),sample({id:"a",location:"Via A"})],legacyLocations=[{id:"z",name:"Via Z"},{id:"a",name:"Via A"}],original=JSON.stringify({legacyExams,legacyLocations}),vault=exams.createStore({legacyStorage:memory({[exams.EXAMS_KEY]:JSON.stringify(legacyExams),[exams.LOCATIONS_KEY]:JSON.stringify(legacyLocations)}),backend});await vault.initialize();await vault.replaceAll(legacyExams,legacyLocations);assert.equal(JSON.stringify({legacyExams,legacyLocations}),original);assert.deepEqual((await vault.exams()).map(item=>item.id),["a","z"]);assert.deepEqual((await vault.exams()).find(item=>item.id==="z").participants.map(item=>item.studentId),["s2","s1"])});
test("verifica canonica copre archivi vuoti singoli multipli e ora finale assente",()=>{const one=[sample({endTime:undefined,extra:undefined})],many=[sample({id:"z",endTime:""}),sample({id:"a"})];assert.equal(exams.archivesEqual([],[],[],[]),true);assert.equal(exams.archivesEqual(one,[],[{...one[0],endTime:""}],exams.DEFAULT_LOCATIONS),true);assert.equal(exams.archivesEqual(many,[{id:"z",name:"Via Z"},{id:"a",name:"Via A"}],[...many].reverse(),[{id:"a",name:"Via A"},{id:"z",name:"Via Z"}]),true)});
test("verifica canonica rileva differenze effettive e replaceAll esegue rollback con secondo tentativo",async()=>{const inner=exams.createMemoryBackend(),backend={...inner,alter:false,async getAll(name){const values=await inner.getAll(name);if(this.alter&&name==="exams"&&values.length)return values.map((item,index)=>index?item:{...item,location:"Alterata"});return values.sort((a,b)=>String(a.id??a.key).localeCompare(String(b.id??b.key)))}};const setup=await store({},backend),before=[sample({id:"before"})];await setup.store.replaceAll(before,[]);backend.alter=true;await assert.rejects(()=>setup.store.replaceAll([sample({id:"z"}),sample({id:"a"})],[]),/Verifica archivio esami/);backend.alter=false;assert.deepEqual((await setup.store.exams()).map(item=>item.id),["before"]);await setup.store.replaceAll([sample({id:"z"}),sample({id:"a"})],[]);assert.deepEqual((await setup.store.exams()).map(item=>item.id),["a","z"])});
