"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),core=require("../examiner-routes.js");
function memoryStorage(){const values=new Map();return{get length(){return values.size},key:index=>[...values.keys()][index]??null,getItem:key=>values.has(key)?values.get(key):null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key),values}}
function route(count=60){return Array.from({length:count},(_,index)=>({lat:44.4+index*.0001,lng:8.9+(index%7)*.00004,accuracy:8,time:1000+index*5000,breakBefore:index===30}))}
test("schema percorso è idempotente e conserva punti, segmenti e report",()=>{const raw={id:"r1",examinerId:"e1",sequence:2,title:" Prova ",note:"Nota",startedAt:1000,endedAt:5000,points:route(4),segments:[0,2],report:{state:"paused",samples:route(3),results:[{sampleIndex:0,routeIndex:0,name:"Via A",status:"identified"}],networkRequests:1,nextIndex:1}};const once=core.normalizeRoute(raw),twice=core.normalizeRoute(once);assert.deepEqual(twice,once);assert.equal(once.points.length,4);assert.equal(once.report.state,"paused")});
test("archivio separa account ed esaminatori e supporta percorsi consecutivi",()=>{const store=core.createStore(memoryStorage());store.saveRoute("a","e1",{id:"r1",examinerId:"e1",startedAt:1,points:route(2)});store.saveRoute("a","e1",{id:"r2",examinerId:"e1",startedAt:2,points:route(3)});assert.deepEqual(store.routes("a","e1").map(x=>x.id),["r1","r2"]);assert.equal(store.routes("b","e1").length,0);assert.equal(store.routes("a","e2").length,0)});
test("limite quindici accetta il quindicesimo e blocca il sedicesimo senza sovrascrivere",()=>{const store=core.createStore(memoryStorage());for(let i=0;i<15;i++)store.saveRoute("a","e",{id:`r${i}`,examinerId:"e",startedAt:i+1,points:route(2)});assert.equal(store.routes("a","e").length,15);assert.throws(()=>store.saveRoute("a","e",{id:"r15",examinerId:"e",startedAt:20,points:route(2)}),/percorsi raggiunto/);assert.equal(store.routes("a","e").length,15);assert.equal(store.routes("a","e")[0].id,"r0")});
test("dopo un'eliminazione è nuovamente possibile salvare un percorso",()=>{const store=core.createStore(memoryStorage());for(let i=0;i<15;i++)store.saveRoute("a","e",{id:`r${i}`,examinerId:"e",startedAt:i+1,points:route(2)});store.deleteRoute("a","e","r7");store.saveRoute("a","e",{id:"r15",examinerId:"e",startedAt:30,points:route(2)});assert.equal(store.routes("a","e").length,15);assert.ok(store.routes("a","e").some(item=>item.id==="r15"))});
test("dati precedenti con dieci percorsi restano compatibili",()=>{const store=core.createStore(memoryStorage()),items=Array.from({length:10},(_,i)=>({id:`old${i}`,examinerId:"e",startedAt:i+1,points:route(2)}));store.restore("a",{version:1,accountId:"a",examiners:{e:items},cache:{}});assert.equal(store.routes("a","e").length,10)});
test("ripristino con quindici percorsi riesce e oltre il limite viene rifiutato senza sostituzione",()=>{const storage=memoryStorage(),store=core.createStore(storage),items=Array.from({length:15},(_,i)=>({id:`r${i}`,examinerId:"e",startedAt:i+1,points:route(2)}));store.restore("a",{version:1,accountId:"a",examiners:{e:items},cache:{}});assert.equal(store.routes("a","e").length,15);assert.throws(()=>store.restore("a",{version:1,accountId:"a",examiners:{e:[...items,{id:"r15",examinerId:"e",startedAt:20,points:route(2)}]},cache:{}}),/15 percorsi/);assert.equal(store.routes("a","e").length,15)});
test("unione elimina ID duplicati entro quindici e rifiuta il superamento senza alterare gli originali",()=>{const existing=Array.from({length:10},(_,i)=>({id:`r${i}`,examinerId:"e",startedAt:i+1,points:route(2)})),within=[...Array.from({length:5},(_,i)=>({id:`r${i+10}`,examinerId:"e",startedAt:i+11,points:route(2)})),existing[0]],merged=core.mergeRoutes(existing,within,"e");assert.equal(merged.length,15);assert.equal(existing.length,10);assert.throws(()=>core.mergeRoutes(existing,Array.from({length:6},(_,i)=>({id:`new${i}`,examinerId:"e",startedAt:i+20,points:route(2)})),"e"),/15 percorsi/);assert.equal(existing.length,10)});
test("eliminazione singola non rinomina o altera gli altri percorsi",()=>{const store=core.createStore(memoryStorage());for(let i=0;i<3;i++)store.saveRoute("a","e",{id:`r${i}`,sequence:i+1,examinerId:"e",startedAt:i+1,points:route(2)});store.deleteRoute("a","e","r1");assert.deepEqual(store.routes("a","e").map(x=>[x.id,x.sequence]),[["r0",1],["r2",3]])});
test("bozze persistono e restano isolate per account ed esaminatore",()=>{const store=core.createStore(memoryStorage());store.saveDraft("a","e1",{id:"draft",examinerId:"e1",startedAt:1,points:route(3)});assert.equal(store.drafts("a","e1").length,1);assert.equal(store.drafts("b","e1").length,0);assert.equal(store.drafts("a","e2").length,0);store.deleteDraft("a","e1","draft");assert.equal(store.drafts("a","e1").length,0)});
test("ricaricamento e ripresa conservano titolo, nota e identità completa della bozza",()=>{const storage=memoryStorage(),before=core.createStore(storage);before.saveDraft("account-collaudo","examiner-1",{id:"draft-1",examinerId:"examiner-1",title:"Percorso prova 1",note:"Nota della bozza",startedAt:1000,durationMs:120000,distanceMetres:42,points:route(2),segments:[0],status:"saved"});const afterReload=core.createStore(storage),resumed=afterReload.drafts("account-collaudo","examiner-1")[0];assert.equal(resumed.title,"Percorso prova 1");assert.equal(resumed.note,"Nota della bozza");assert.equal(resumed.id,"draft-1");assert.equal(resumed.examinerId,"examiner-1");assert.equal(resumed.startedAt,1000);assert.equal(resumed.points.length,2);assert.equal(afterReload.drafts("altro-account","examiner-1").length,0);assert.equal(afterReload.drafts("account-collaudo","altro-esaminatore").length,0)});
test("coordinatore consente una sola registrazione GPS",()=>{const lock=core.createGpsCoordinator();assert.equal(lock.acquire("lesson"),true);assert.equal(lock.acquire("examiner"),false);assert.equal(lock.current(),"lesson");lock.release("lesson");assert.equal(lock.acquire("examiner"),true)});
test("campionamento adattivo supera 26 e non supera 40",()=>{const samples=core.adaptiveSamples(route(140),40);assert.ok(samples.length>26);assert.ok(samples.length<=40);assert.equal(samples[0].routeIndex,0);assert.equal(samples.at(-1).routeIndex,139);assert.ok(samples.some(x=>x.breakBefore))});
test("deduplicazione spaziale evita richieste quasi identiche",()=>{const samples=core.deduplicateSamples([{lat:44,lng:8,accuracy:1,time:1,routeIndex:0},{lat:44.000001,lng:8.000001,accuracy:1,time:2,routeIndex:1},{lat:44.001,lng:8.001,accuracy:1,time:3,routeIndex:2}]);assert.equal(samples[0].duplicateOf,null);assert.equal(samples[1].duplicateOf,0);assert.equal(samples[2].duplicateOf,null)});
test("report usa cache, una richiesta alla volta e salva avanzamento",async()=>{let active=0,maxActive=0,calls=0,progress=0;const cache={[core.cacheKey(core.adaptiveSamples(route(35),40)[0])]:{name:"Via Cache",locality:"Genova",savedAt:1,lastUsedAt:1}},result=await core.runReport({route:route(35),report:null,cache,config:{enabled:true,maxRequests:40,intervalMs:1250},sleep:async()=>{},request:async()=>{active++;maxActive=Math.max(maxActive,active);calls++;active--;return{name:`Via ${calls}`,locality:"Genova"}},onProgress:()=>progress++});assert.equal(maxActive,1);assert.ok(result.report.cacheHits>=1);assert.equal(result.report.networkRequests,calls);assert.ok(progress>0);assert.match(result.report.state,/completed/)});
test("massimo 40 richieste include i retry",async()=>{let calls=0;const result=await core.runReport({route:route(100),report:null,cache:{},config:{enabled:true,maxRequests:40,intervalMs:1250},sleep:async()=>{},request:async()=>{calls++;throw new Error("rete")}});assert.equal(calls,40);assert.equal(result.report.networkRequests,40);assert.ok(["temporary_error","completed_with_unidentified"].includes(result.report.state))});
test("HTTP 429 sospende subito senza retry o fallback",async()=>{let calls=0;const result=await core.runReport({route:route(35),report:null,cache:{},config:{enabled:true,maxRequests:40,intervalMs:1250},sleep:async()=>{},request:async()=>{calls++;return{status:429}}});assert.equal(calls,1);assert.equal(result.report.state,"paused");assert.match(result.report.lastError,/Nessun servizio a pagamento/)});
test("retry ignora cache negativa, conserva positivi e incrementa richieste cumulative",async()=>{const points=route(2),samples=core.deduplicateSamples(core.adaptiveSamples(points,40)),report=core.normalizeReport({state:"completed_with_unidentified",samples,results:[{sampleIndex:0,routeIndex:0,name:"Via positiva",status:"identified",attempts:1},{sampleIndex:1,routeIndex:1,name:"",status:"unidentified",attempts:1}],networkRequests:36,nextIndex:2}),retry=core.normalizeReport({...report,state:"paused",results:report.results.filter(x=>x.status==="identified"),nextIndex:0}),negative={[core.cacheKey(samples[1])]:{name:"",locality:"",savedAt:1,lastUsedAt:1}},cache=core.normalizeCache(negative);let calls=0;const result=await core.runReport({route:points,report:retry,cache,config:{enabled:true,maxRequests:40,intervalMs:1250},sleep:async()=>{},request:async()=>{calls++;return{name:"Via risolta",locality:"Genova"}}});assert.equal(calls,1);assert.equal(result.report.networkRequests,37);assert.equal(result.report.results.find(x=>x.sampleIndex===0).name,"Via positiva");assert.equal(result.report.results.find(x=>x.sampleIndex===1).name,"Via risolta");assert.equal(result.report.state,"completed")});
test("retry irrisolto usa al massimo le richieste residue e termina",async()=>{const points=route(2),samples=core.deduplicateSamples(core.adaptiveSamples(points,40)),report=core.normalizeReport({state:"paused",samples,results:[{sampleIndex:0,routeIndex:0,name:"Via positiva",status:"identified"}],networkRequests:39,nextIndex:0});let calls=0;const result=await core.runReport({route:points,report,cache:{},config:{enabled:true,maxRequests:40,intervalMs:1250},sleep:async()=>{},request:async()=>{calls++;throw new Error("non identificato")}});assert.equal(calls,1);assert.equal(result.report.networkRequests,40);assert.equal(result.report.state,"completed_with_unidentified");assert.equal(result.report.results.filter(x=>x.sampleIndex===1).length,1)});
test("retry si arresta immediatamente su HTTP 429 e persiste dopo ricaricamento",async()=>{const points=route(2),samples=core.deduplicateSamples(core.adaptiveSamples(points,40)),report=core.normalizeReport({state:"paused",samples,results:[{sampleIndex:0,routeIndex:0,name:"Via positiva",status:"identified"}],networkRequests:36,nextIndex:0});let calls=0;const result=await core.runReport({route:points,report,cache:{},config:{enabled:true,maxRequests:40,intervalMs:1250},sleep:async()=>{},request:async()=>{calls++;return{status:429}}});assert.equal(calls,1);assert.equal(result.report.networkRequests,37);assert.equal(result.report.state,"paused");const storage=memoryStorage(),store=core.createStore(storage);store.saveRoute("a","e",{id:"r",examinerId:"e",startedAt:1,points,report:result.report});const reloaded=core.createStore(storage).routes("a","e")[0];assert.equal(reloaded.report.networkRequests,37);assert.equal(reloaded.report.state,"paused")});
test("interruzione e ripresa non ripetono risultati già risolti",async()=>{let calls=0,controller=new AbortController();const first=await core.runReport({route:route(35),report:null,cache:{},config:{enabled:true,maxRequests:40,intervalMs:1250},sleep:async()=>{},signal:controller.signal,request:async()=>{calls++;if(calls===3)controller.abort();return{name:`Via ${calls}`}}});const before=first.report.results.length;controller=new AbortController();const second=await core.runReport({route:route(35),report:first.report,cache:first.cache,config:{enabled:true,maxRequests:40,intervalMs:1250},sleep:async()=>{},signal:controller.signal,request:async()=>{calls++;return{name:`Via ${calls}`}}});assert.ok(second.report.results.length>before);assert.equal(new Set(second.report.results.map(x=>x.sampleIndex)).size,second.report.results.length)});
test("ritorno successivo sulla stessa via resta una nuova occorrenza",()=>{const points=route(5),report=core.normalizeReport({state:"completed",samples:points.map((p,i)=>({...p,routeIndex:i})),results:[{sampleIndex:0,routeIndex:0,name:"Via A",status:"identified"},{sampleIndex:1,routeIndex:1,name:"Via B",status:"identified"},{sampleIndex:2,routeIndex:2,name:"Via A",status:"identified"}]});assert.deepEqual(core.buildSegments(points,report).map(x=>x.name),["Via A","Via B","Via A"])});
test("kill switch impedisce ogni richiesta",async()=>{let calls=0;await assert.rejects(()=>core.runReport({route:route(40),report:null,cache:{},config:{enabled:false},request:async()=>{calls++}}),/temporaneamente non disponibile/);assert.equal(calls,0)});
test("normalizzazione rifiuta coordinate non valide senza perdere il percorso",()=>{const normalized=core.normalizeRoute({id:"r",examinerId:"e",startedAt:1,points:[{lat:NaN,lng:8,accuracy:1,time:1},...route(2)]});assert.equal(normalized.points.length,2)});
