const test=require("node:test"),assert=require("node:assert/strict"),exams=require("C:/agenda_zena/Agenda-Istruttori-v1-21-LAVORO/exams.js"),multi=require("C:/agenda_zena/Agenda-Istruttori-v1-21-LAVORO/student-multi-import.js");
function memory(){const map=new Map;return{getItem:key=>map.has(key)?map.get(key):null,setItem:(key,value)=>map.set(key,String(value))}}
const sample=(overrides={})=>({id:"exam-1",date:"2026-09-14",startTime:"09:00",endTime:"11:00",location:"Via Bobbio",participants:[{studentId:"s1",outcome:"",rejectionNote:""}],createdAt:1,updatedAt:1,...overrides});
test("crea e modifica una sessione valida conservando la località storica",()=>{const store=exams.createStore(memory(),{idFactory:()=>"id"}),saved=store.saveExam(sample());store.saveLocation({id:"loc",name:"Via Storica"});store.saveLocation({id:"loc",name:"Via Nuova"});assert.equal(store.exams()[0].location,"Via Bobbio");store.saveExam({...saved,endTime:"12:00"});assert.equal(store.exams()[0].endTime,"12:00")});
test("valida data orari e impedisce partecipanti duplicati",()=>{assert.throws(()=>exams.normalizeExam(sample({date:"14/09/2026"}),{strict:true}),/non valida/);assert.throws(()=>exams.normalizeExam(sample({endTime:"08:00"}),{strict:true}),/non valida/);assert.throws(()=>exams.normalizeExam(sample({participants:[{studentId:"s1"},{studentId:"s1"}]}),{strict:true}),/duplicato/)});
test("esito iniziale vuoto, opzioni esclusive e nota di respingimento preservata",()=>{const normalized=exams.normalizeExam(sample({participants:[{studentId:"s1",outcome:"R",rejectionNote:"Nota lunga ".repeat(80)}]}),{strict:true});assert.equal(normalized.participants[0].outcome,"R");assert.match(normalized.participants[0].rejectionNote,/Nota lunga/);assert.equal(exams.outcomeLabel(""),"Esito non inserito");assert.equal(exams.outcomeLabel("I"),"Idoneo");assert.equal(exams.outcomeLabel("A"),"Assente")});
test("filtra i trasferimenti senza esporre altri partecipanti",()=>{const filtered=exams.forStudents([sample({participants:[{studentId:"s1",outcome:"I"},{studentId:"s2",outcome:"R",rejectionNote:"privata"}]})],["s1"]);assert.equal(filtered.length,1);assert.deepEqual(filtered[0].participants,[{studentId:"s1",outcome:"I",rejectionNote:""}])});
test("import multiplo rimappa Crea copia e aggiorna senza duplicare collegamenti",async()=>{const envelope=await multi.validate({app:"Agenda Istruttore",version:"1.21.0",type:"students",students:[{id:"s1",lessons:[],checklist:[]}],exams:[sample()],documents:[]});let n=0;const copied=multi.plan([{id:"s1"}],envelope,{s1:"copy"},prefix=>`${prefix}-${++n}`,[sample()]);assert.notEqual(copied.students[1].id,"s1");assert.equal(copied.exams.length,2);assert.equal(copied.exams[1].participants[0].studentId,copied.students[1].id);const updated=multi.plan([{id:"s1"}],envelope,{s1:"update"},prefix=>`${prefix}-${++n}`,[sample({participants:[{studentId:"s1",outcome:""}]})]);assert.equal(updated.exams.length,1);assert.equal(updated.exams[0].participants[0].studentId,"s1")});
test("vecchi trasferimenti senza esami restano compatibili",async()=>{const envelope=await multi.validate({app:"Agenda Istruttore",version:"1.21.0",type:"students",students:[{id:"old",lessons:[],checklist:[]}]});assert.deepEqual(envelope.exams,[])});
test("una sessione con più nuovi allievi resta unica e senza partecipanti duplicati",async()=>{const envelope=await multi.validate({app:"Agenda Istruttore",version:"1.21.0",type:"students",students:[{id:"s1",lessons:[],checklist:[]},{id:"s2",lessons:[],checklist:[]}],exams:[sample({participants:[{studentId:"s1",outcome:"I"},{studentId:"s2",outcome:"",rejectionNote:"nota conservata"}]})]});let n=0;const plan=multi.plan([],envelope,{},kind=>`${kind}-${++n}`,[]);assert.equal(plan.exams.length,1);assert.equal(plan.exams[0].participants.length,2);assert.equal(new Set(plan.exams[0].participants.map(item=>item.studentId)).size,2)});
test("rollback dell'importazione ripristina anche gli esami",async()=>{const originalStudents=[{id:"old"}],originalExams=[sample()],writes=[];const plan={students:[{id:"new"}],documents:[],exams:[sample({id:"new-exam"})],counts:{created:1,updated:0,skipped:0}},adapter={readStudents:async()=>structuredClone(originalStudents),readExams:async()=>structuredClone(originalExams),snapshotDocuments:async()=>[],writeDocuments:async()=>{},restoreDocuments:async()=>{},writeStudents:async value=>writes.push(["students",structuredClone(value)]),writeExams:async value=>{writes.push(["exams",structuredClone(value)]);if(value[0]?.id==="new-exam")throw Error("guasto simulato")}};await assert.rejects(()=>multi.apply(plan,adapter),/dati precedenti/);assert.deepEqual(writes.at(-1),["exams",originalExams]);assert.deepEqual(writes.at(-2),["students",originalStudents])});
test("località iniziali sono disponibili e una rinomina non altera le sessioni",()=>{const storage=memory(),store=exams.createStore(storage,{idFactory:()=>"custom"});assert.deepEqual(store.locations().map(item=>item.name),exams.DEFAULT_LOCATIONS);const bobbio=store.locations().find(item=>item.name==="Via Bobbio");store.saveExam(sample());store.saveLocation({...bobbio,name:"Via Bobbio nuova"});assert.ok(store.locations().some(item=>item.name==="Via Bobbio nuova"));assert.equal(store.exams()[0].location,"Via Bobbio")});
