const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),root="C:/agenda_zena/Agenda-Istruttori-v1-21-LAVORO",read=file=>fs.readFileSync(path.join(root,file),"utf8");
test("Altre funzioni espone ESAMI e tutte le schermate richieste",()=>{const html=read("index.html");assert.match(html,/id="openExaminers"[\s\S]*?id="openExams"/);for(const id of ["exams","newExam","examForm","examDate","examStartTime","examEndTime","examLocation","selectExamExaminer","removeExamExaminer","examExaminerPicker","examExaminerPickerList","confirmExamExaminer","addExamStudents","examParticipants","examStudentPicker","examLocations"])assert.match(html,new RegExp(`id="${id}"`))});
test("UI usa ID stabili, selezione multipla accessibile ed esiti esclusivi",()=>{const app=read("app.js");assert.match(app,/participant\.studentId/);assert.match(app,/type="radio" name="\$\{group\}"/);assert.match(app,/multi-student-option exam-student-option/);assert.match(app,/L’allievo resterà nell’archivio/);assert.match(app,/participant\.outcome=input\.value/);assert.doesNotMatch(app,/participant\.rejectionNote=""/)});
test("PDF include esami e casi completi senza duplicare la fonte",()=>{const report=read("r10-features.js"),model=read("exams.js");for(const value of ["studentExamsReportHtml","Motivazione:","ESAMI ("])assert.match(report,new RegExp(value.replace(/[()]/g,"\\$&")));assert.match(model,/Esito non inserito/);assert.match(report,/state\.exams/);assert.match(report,/overflow-wrap:anywhere/)});
test("backup formato 4 aggiunge campi opzionali senza toccare parser progressivo",()=>{const backup=read("full-backup.js"),stream=read("full-backup-stream.js");assert.match(backup,/FORMAT_VERSION=4/);assert.match(backup,/AgendaExamStore\.snapshot/);assert.match(backup,/AgendaExamStore\.replaceAll/);assert.match(backup,/appData\.exams\|\|\[\]/);assert.match(stream,/parseLegacyBackup/)});
test("caricamento protetto inserisce exams prima dell'app e attende IndexedDB",()=>{const auth=read("auth-client.js"),exam=auth.indexOf('"exams.js'),app=auth.indexOf('"app.js');assert.ok(exam>=0&&exam<app);assert.match(auth,/AgendaAppReady/)});

test("orari testuali mobile e fine facoltativa",()=>{const html=read("index.html"),css=read("style.css"),app=read("app.js");assert.match(html,/examStartTime" type="text" inputmode="decimal" autocomplete="off"/);assert.match(html,/Ora di fine \(facoltativa\)/);assert.match(css,/exam-form-view input[^}]*font-size:16px/);assert.match(app,/Ora fine non inserita/)});

test("elenco ESAMI mostra ultimo, espande e conserva lo stato",()=>{const html=read("index.html"),app=read("app.js");assert.match(html,/id="toggleExams"[^>]+aria-expanded="false"/);assert.match(html,/Nessun esame salvato\. Premi NUOVO ESAME/);assert.match(app,/function compareExamsNewestFirst/);assert.match(app,/String\(b\.date/);assert.match(app,/String\(b\.startTime/);assert.match(app,/updatedAt/);assert.match(app,/createdAt/);assert.match(app,/localeCompare\(String\(b\.id/);assert.match(app,/state\.examsExpanded\?sorted:sorted\.slice\(0,1\)/);assert.match(app,/sorted\.length<2/);assert.match(app,/MOSTRA SOLO L’ULTIMO/);assert.match(app,/VISUALIZZA TUTTI GLI ESAMI/);assert.match(app,/state\.examsExpanded=!state\.examsExpanded/);const back=app.match(/\$\("backExamForm"\)\.onclick=\(\)=>\{renderExams\(\);show\("exams"\)\}/);assert.ok(back,"INDIETRO deve renderizzare senza azzerare examsExpanded")});

test("ordinamento ESAMI è deterministico per data ora aggiornamento creazione e ID",()=>{const app=read("app.js"),source=app.match(/function compareExamsNewestFirst\(a,b\)\{[^\n]+\}/)?.[0];assert.ok(source);const compare=Function(`${source};return compareExamsNewestFirst`)(),items=[{id:"z",date:"2026-09-10",startTime:"09:00",createdAt:1,updatedAt:1},{id:"old",date:"2026-09-09",startTime:"18:00",createdAt:9,updatedAt:9},{id:"b",date:"2026-09-10",startTime:"09:00",createdAt:2,updatedAt:3},{id:"a",date:"2026-09-10",startTime:"09:00",createdAt:2,updatedAt:3},{id:"late",date:"2026-09-10",startTime:"10:00",createdAt:1,updatedAt:1}];assert.deepEqual(items.sort(compare).map(x=>x.id),["late","a","b","z","old"])});
test("zero uno e più esami hanno controlli coerenti",()=>{const app=read("app.js");assert.match(app,/sorted\.length>0/);assert.match(app,/sorted\.length<2/);assert.match(app,/sorted\.slice\(0,1\)/);assert.match(app,/for\(const exam of visible\)/)});
test("selezione esaminatore è singola, sostituibile, rimovibile e annullabile",()=>{const html=read("index.html"),app=read("app.js");assert.match(app,/input\.type="radio"/);assert.match(app,/input\.name="exam-examiner-choice"/);assert.match(app,/state\.examDraft\.examinerId=examiner\.id/);assert.match(app,/state\.examDraft\.examinerName=examinerSnapshotName\(examiner\)/);assert.match(app,/function removeExamExaminer\(\).*examinerId="".*examinerName=""/);assert.match(app,/backExamExaminerPicker.*renderExamForm\(\).*show\("examForm"\)/);assert.match(html,/SELEZIONA ESAMINATORE/);assert.match(html,/RIMUOVI SELEZIONE/)});
test("nuovo esame richiede esaminatore ma lo storico resta compatibile",()=>{const app=read("app.js"),model=read("exams.js");assert.match(app,/!state\.editingExam&&!state\.examDraft\.examinerId.*Seleziona un esaminatore prima di salvare il nuovo esame/);assert.match(model,/examinerId:clean\(raw\?\.examinerId\)/);assert.match(model,/examinerName:clean\(raw\?\.examinerName\)/)});
test("riepilogo mostra esaminatore dopo partecipanti e scheda conserva fotografia storica",()=>{const app=read("app.js");assert.match(app,/N\. partecipanti: \$\{exam\.participants\.length\}[\s\S]*?Esaminatore: \$\{esc\(examHistoricalExaminerName\(exam\)\)\}/);assert.match(app,/selectedExaminerName.*Esaminatore:/);assert.match(app,/non inserito/)});
test("PDF mostra esaminatore per Idoneo Respinto Assente ed esito non inserito",()=>{const report=read("r10-features.js");assert.match(report,/outcome=window\.AgendaExams\.outcomeLabel/);assert.match(report,/examiner=String\(exam\.examinerName/);assert.match(report,/<dt>Esito<\/dt>[\s\S]*?<dt>Esaminatore<\/dt>/);assert.ok(report.indexOf("examiner=String")<report.indexOf('participant?.outcome==="R"'),"l'esaminatore deve essere indipendente dall'esito Respinto");assert.match(report,/non inserito/)});
test("selettore esaminatore è responsive e touch friendly senza overflow",()=>{const css=read("style.css");assert.match(css,/exam-examiner-picker-view[^}]*overflow-x:hidden/);assert.match(css,/exam-examiner-selection button\{[^}]*min-height:48px/);assert.match(css,/exam-examiner-selection>div[^}]*grid-template-columns:1fr/);assert.match(css,/overflow-wrap:anywhere/)});
