"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const stream=require("../full-backup-stream.js");
function documentRecord(index,bytes=Buffer.from(`documento-${index}`)){return{id:`doc-${index}`,originalName:`documento-${index}.bin`,title:`Documento ${index}`,mimeType:"application/octet-stream",size:bytes.length,createdAt:1,section:"common",sha256:crypto.createHash("sha256").update(bytes).digest("hex"),dataBase64:bytes.toString("base64")}}
function payload(version=4,documents=[]){return{format:"AgendaIstruttoriFullBackup",formatVersion:version,app:"Agenda Istruttori",appVersion:"1.21.0",createdAt:"2026-09-08T00:00:00.000Z",metadata:{students:0,documents:documents.length,approximateBytes:0},appData:{students:[],checklists:{},examiners:[]},...(version>=3?{examinerRoutes:{version:1,routes:[]}}:{}),...(version>=4?{drivingErrorCatalog:{version:1,categories:[]}}:{}),documents}}
async function parse(value,options={}){const file=new Blob([JSON.stringify(value)]),out=[];const result=await stream.parseLegacyBackup(file,{chunkBytes:options.chunkBytes||64*1024,signal:options.signal,onDocumentStart:(meta,i)=>out[i]={meta,chunks:[],size:0},onDocumentChunk:(meta,bytes,i)=>{out[i].chunks.push(bytes.length);out[i].size+=bytes.length},onDocumentEnd:(meta,verified,i)=>out[i].verified=verified});return{...result,documents:out,fileSize:file.size}}
test("formati storici 1, 2, 3 e 4 conservano bytes e checksum",async()=>{for(const version of [1,2,3,4]){const record=documentRecord(version),result=await parse(payload(version,[record]));assert.equal(result.header.formatVersion,version);assert.equal(result.documents[0].size,record.size);assert.equal(result.documents[0].verified.sha256,record.sha256)}});
test("Base64 diviso nei punti critici conserva i gruppi di quattro",async()=>{const bytes=crypto.randomBytes(257),value=payload(4,[documentRecord(1,bytes)]);for(const chunkBytes of [65536,65537,65538,65539])assert.equal((await parse(value,{chunkBytes})).documents[0].size,bytes.length)});
test("buffer limitato anche per documento grande",async()=>{const bytes=Buffer.alloc(6*1024*1024),result=await parse(payload(4,[documentRecord(1,bytes)]),{chunkBytes:128*1024});assert.equal(result.documents[0].size,bytes.length);assert.ok(result.maxBufferedChars<300*1024);assert.ok(result.documents[0].chunks.length>20)});
test("checksum errato, file troncato e annullamento sono rifiutati",async()=>{const record=documentRecord(1);await assert.rejects(parse(payload(4,[{...record,sha256:"0".repeat(64)}])),/integrità/);const text=JSON.stringify(payload(4,[record]));await assert.rejects(stream.parseLegacyBackup(new Blob([text.slice(0,-10)])),/troncato|chiusura|Base64/);const controller=new AbortController();controller.abort();await assert.rejects(stream.parseLegacyBackup(new Blob([text]),{signal:controller.signal}),/annullato/)});
test("50, 128, 129 e 341 MB non incontrano soglie applicative",()=>{for(const mb of [50,128,129,341])assert.equal(stream.estimateBinaryBytes(mb*1024*1024),Math.ceil(mb*1024*1024*.75))});
test("spazio sufficiente, insufficiente e API assente",async()=>{const enough=await stream.estimateCapacity(100,20,{estimate:async()=>({quota:1000,usage:100})}),low=await stream.estimateCapacity(1000,500,{estimate:async()=>({quota:1000,usage:900})}),unknown=await stream.estimateCapacity(100,20,null);assert.equal(enough.sufficient,true);assert.equal(low.sufficient,false);assert.equal(unknown.supported,false)});
test("errore quota interrompe prima della conclusione",async()=>{const error=new Error("quota");error.name="QuotaExceededError";let ended=false;await assert.rejects(stream.parseLegacyBackup(new Blob([JSON.stringify(payload(4,[documentRecord(1,Buffer.alloc(200000))]))]),{chunkBytes:65536,onDocumentChunk:()=>{throw error},onDocumentEnd:()=>ended=true}),error);assert.equal(ended,false)});
test("nessun Base64 completo viene materializzato",()=>{const source=fs.readFileSync(path.join(__dirname,"..","full-backup-stream.js"),"utf8");assert.match(source,/onDocumentChunk/);assert.doesNotMatch(source,/JSON\.parse\(buffer\.slice\(documentStart/);assert.doesNotMatch(source,/await file\.text\(\)|readAsText|file\.arrayBuffer\(\)/)});
