"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const stream=require("../full-backup-stream.js");
function payload(version=4,documents=[]){return{format:"AgendaIstruttoriFullBackup",formatVersion:version,app:"Agenda Istruttori",appVersion:"1.21.0",createdAt:"2026-09-08T00:00:00.000Z",metadata:{students:0,documents:documents.length,approximateBytes:0},appData:{students:[],checklists:{},examiners:[]},...(version>=3?{examinerRoutes:{version:1,routes:[]}}:{}),...(version>=4?{drivingErrorCatalog:{version:1,categories:[]}}:{}),documents}}
function documentRecord(index,size=128){return{id:`doc-${index}`,originalName:`documento-${index}.bin`,title:`Documento ${index}`,mimeType:"application/octet-stream",size,createdAt:1,section:"common",sha256:"0".repeat(64),dataBase64:"A".repeat(Math.ceil(size/3)*4)}}
async function parse(value,options={}){const file=new Blob([JSON.stringify(value)],{type:"application/json"}),documents=[];file.name="test.agendabackup";const result=await stream.parseLegacyBackup(file,{...options,onDocument:item=>documents.push(item)});return{...result,documents,fileSize:file.size}}
test("formati legacy 1, 2, 3 e 4 sono letti progressivamente",async()=>{for(const version of [1,2,3,4]){const result=await parse(payload(version,[documentRecord(version)]),{chunkBytes:64*1024});assert.equal(result.header.formatVersion,version);assert.equal(result.count,1)}});
test("molti documenti piccoli non richiedono il JSON monolitico",async()=>{const records=Array.from({length:80},(_,index)=>documentRecord(index,32*1024)),result=await parse(payload(4,records),{chunkBytes:64*1024});assert.equal(result.count,80);assert.ok(result.maxBufferedChars<result.fileSize/4)});
test("pochi documenti grandi e documento singolo vengono conservati integralmente",async()=>{for(const records of [[documentRecord(1,2*1024*1024),documentRecord(2,3*1024*1024)],[documentRecord(1,5*1024*1024)]]){const result=await parse(payload(4,records),{chunkBytes:128*1024});assert.equal(result.count,records.length);assert.deepEqual(result.documents.map(item=>item.dataBase64.length),records.map(item=>item.dataBase64.length))}});
test("50, 128, 129 e 341 MB non incontrano soglie applicative",()=>{for(const mb of [50,128,129,341])assert.equal(stream.estimateBinaryBytes(mb*1024*1024),Math.ceil(mb*1024*1024*.75))});
test("spazio sufficiente, insufficiente e API assente",async()=>{const enough=await stream.estimateCapacity(100,20,{estimate:async()=>({quota:1000,usage:100})}),low=await stream.estimateCapacity(1000,500,{estimate:async()=>({quota:1000,usage:900})}),unknown=await stream.estimateCapacity(100,20,null);assert.equal(enough.sufficient,true);assert.equal(low.sufficient,false);assert.equal(unknown.supported,false)});
test("file troncato e annullamento vengono rifiutati",async()=>{const truncated=new Blob([JSON.stringify(payload(4,[documentRecord(1)])).slice(0,-10)]);await assert.rejects(stream.parseLegacyBackup(truncated),/troncato|corrotto|inattesi/);const controller=new AbortController();controller.abort();await assert.rejects(stream.parseLegacyBackup(new Blob([JSON.stringify(payload())]),{signal:controller.signal}),/annullato/)});
test("il modulo usa letture a blocchi e non file.text globale",()=>{const source=fs.readFileSync(path.join(__dirname,"..","full-backup-stream.js"),"utf8");assert.match(source,/file\.slice\(start,end\)\.text\(\)/);assert.doesNotMatch(source,/await file\.text\(\)|readAsText|arrayBuffer\(\)/)});
