"use strict";
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const gps=require('../lesson-gps.js'),road=fs.readFileSync(path.join(__dirname,'../r10-features.js'),'utf8');
const c=vm.createContext({MAX_ROAD_REQUESTS:Number(road.match(/const MAX_ROAD_REQUESTS=(\d+)/)[1]),ROAD_SAMPLE_MIN_METRES:15,distance:gps.distance});
for(const name of ['sampleRoute','confirmedRoads','routeDistance','routeDuration','routeSamplingWarning']){const start=road.indexOf('  function '+name+'('),end=road.indexOf('\n  }',start)+4;vm.runInContext(road.slice(start,end),c)}
const point=(x,time,accuracy=8)=>({lat:44.4+x/111195,lng:8.9,accuracy,time});
function journey(){const f=gps.create(),out=[];for(let i=0;i<=1284;i++){const p={...point(i*24.4,1000+i*5000,i%17<6?75:20),lng:8.9+Math.sin(i/8)*.0003},observed=f.observe(p,i%13===0?0:4.88);if(observed.accept)out.push(observed.point)}return out}
test('107 minuti e 31 km conservano centinaia di punti e decine di vie distribuite',()=>{
 const route=journey(),samples=c.sampleRoute(route),results=samples.map(p=>({name:'Via sintetica '+Math.floor((p.lat-44.4)*111195/500)})),names=c.confirmedRoads(samples,results);
 assert.ok(route.length>=1000,'punti: '+route.length);assert.ok(samples.length>=60);assert.ok(names.length>=45,'vie: '+names.length);assert.ok(Math.abs(route.at(-1).lat-point(31329.6,0).lat)<.001);
 console.log(JSON.stringify({syntheticMinutes:107,syntheticKm:c.routeDistance(route)/1000,retainedPoints:route.length,reportSamples:samples.length,syntheticStreets:names.length}));
});
test('veicolo fermo con jitter non accumula distanza',()=>{const f=gps.create();let count=0;for(let i=0;i<1000;i++)if(f.observe(point(Math.sin(i)*2,1000+i*5000),0).accept)count++;assert.equal(count,1)});
test('jitter ampio coerente con bassa precisione e velocità assente resta fermo',()=>{const f=gps.create();let count=0;for(let i=0;i<1000;i++)if(f.observe(point(Math.sin(i)*45,1000+i*5000,100),null).accept)count++;assert.equal(count,1)});
test('precisione degradata e velocità istantanea incoerente non interrompono il tracciato',()=>{const f=gps.create(),out=[];for(let i=0;i<80;i++){const v=f.observe(point(i*20,1000+i*5000,i>10&&i<60?150:8),i%3?4:0);if(v.accept)out.push(v.point)}assert.ok(out.length>=50);assert.equal(out.filter(p=>p.breakBefore).length,0);assert.ok(out.some(p=>p.accuracy===150))});
test('galleria chiude un solo segmento, recupero confermato senza ponte',()=>{const f=gps.create(),out=[];for(const p of [point(0,1000),point(20,6000),point(1000,126000),point(1020,131000),point(1040,136000)]){const v=f.observe(p,4);if(v.accept)out.push(v.point)}assert.equal(out.length,4);assert.equal(out[2].breakBefore,true);assert.equal(out[3].breakBefore,false);const names=c.confirmedRoads(out,out.map(()=>({name:'Via sintetica'})));assert.deepEqual(Array.from(names),['Via sintetica','Tratto con segnale GPS insufficiente','Via sintetica'])});
test('salto impossibile isolato non avvelena i punti successivi',()=>{const f=gps.create();f.observe(point(0,1000),4);f.observe(point(20,6000),4);assert.equal(f.observe(point(10000,7000),4).accept,false);const recovered=f.observe(point(40,11000),4);assert.equal(recovered.accept,true);assert.equal(recovered.breakBefore,false);assert.equal(f.observe(point(60,16000),4).accept,true)});
test('vie singole e ritorno sulla stessa via, sconosciuto distinto da gap',()=>{const names=c.confirmedRoads([{}, {}, {}, {}, {},{breakBefore:true},{}],[{name:'A'},{name:'A'},{name:'B'},{name:'A'},{name:''},{name:'C'},{name:'C'}]);assert.deepEqual(Array.from(names),['A','B','A','Tratto non identificato','Tratto con segnale GPS insufficiente','C'])});
test('campionamento storico e segmentato non muta dati e conserva ritorni geografici',()=>{const route=Array.from({length:300},(_,i)=>({...point((i%100)*20,i*5000),breakBefore:i===100||i===200})),before=JSON.stringify(route),samples=c.sampleRoute(route);assert.equal(JSON.stringify(route),before);assert.ok(samples.filter(p=>p.breakBefore).length===2);assert.ok(samples.length>=60);assert.equal(c.sampleRoute([]).length,0);assert.equal(c.sampleRoute([route[0]]).length,1)});
test('diagnostica 31,3 km e 26 punti avverte ma non altera lo storico',()=>{const route=Array.from({length:26},(_,i)=>point(i*31300/25,1000+i*107*60000/25)),before=JSON.stringify(route);assert.match(c.routeSamplingWarning(route),/molto rado/);assert.equal(JSON.stringify(route),before);assert.equal(c.routeSamplingWarning(journey()),'')});
test('tre fix coerenti recuperano un ancoraggio errato senza unire il salto',()=>{const f=gps.create();f.observe(point(0,1000),4);assert.equal(f.observe(point(10000,6000),4).accept,false);assert.equal(f.observe(point(10020,11000),4).accept,false);const recovered=f.observe(point(10040,16000),4);assert.equal(recovered.accept,true);assert.equal(recovered.breakBefore,true);assert.equal(f.observe(point(10060,21000),4).breakBefore,false)});
test('sosta lunga con segnale continuo non crea un falso segmento',()=>{const f=gps.create();f.observe(point(0,1000),0);for(let i=1;i<150;i++)assert.equal(f.observe(point(Math.sin(i),1000+i*1000),0).accept,false);const out=f.observe(point(20,152000),4);assert.equal(out.accept,true);assert.equal(out.breakBefore,false)});
test('report HTTP 429 si ferma senza retry e rende esplicito il risultato parziale',async()=>{let calls=0;const nodes=new Map(),get=id=>{if(!nodes.has(id))nodes.set(id,{classList:{add(){},remove(){}},setAttribute(){}});return nodes.get(id)};const ctx=vm.createContext({window:{},navigator:{onLine:true},lesson:()=>({route:[point(0,1),point(30,5000)],createdAt:1}),student:()=>({}),$:get,sampleRoute:r=>r,loadRoadCache:()=>({}),reverseRoad:async()=>{calls++;const e=Error('limited');e.status=429;throw e},confirmedRoads:c.confirmedRoads,routeDistance:c.routeDistance,routeDuration:c.routeDuration,routeSamplingWarning:c.routeSamplingWarning,nameOf:()=> 'Fittizio',esc:String,formatDistance:String,formatDuration:String,reportItemLabel:x=>x||'Non disponibile',setTimeout});const start=road.indexOf('  async function generateRoadReport('),end=road.indexOf('\n  }',start)+4;vm.runInContext(road.slice(start,end),ctx);await ctx.generateRoadReport();assert.equal(calls,1);assert.match(get('roadReportStatus').textContent,/report parziale/);assert.equal(get('generateRoadReport').disabled,false)});
