"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),vm=require("node:vm"),fs=require("node:fs"),Drafts=require("../lesson-drafts.js");
const source=fs.readFileSync(require("node:path").join(__dirname,"../app.js"),"utf8");
function fixture({cleanupFails=false}={}){
 const student={id:"synthetic-student",lessons:[]},state={studentId:student.id,lessonId:null,errorDraftLessonId:"synthetic-lesson",tempRoute:[{lat:44,lng:8}],tempErrors:[]};
 let persisted=[],saved=0,removed=0,open=0;const alerts=[];
 const fields={lessonDate:{value:"2026-09-01"},lessonTime:{value:"13:00"},lessonDuration:{value:"30"},lessonNotes:{value:"NOTA FITTIZIA"},lessonChecklist:{dataset:{items:"[]"}}};
 const context=vm.createContext({lessonActivityDraft:null,studentSaving:false,lessonDraftReady:true,lessonStartedAt:1,state,window:{AgendaAuth:{currentUser:()=>({id:"synthetic-account",name:"ISTRUTTORE FITTIZIO",role:"ISTRUTTORE"})},LessonDrafts:Drafts},validLessonStudent:()=>true,student:()=>student,lesson:()=>student.lessons.find(x=>x.id===state.lessonId),drivingErrorAccountId:()=>"synthetic-account",persistLessonSession:async()=>{},stopGps(){},$:id=>fields[id],DRIVING_ERRORS:{normalizeErrors:x=>x},uid:()=>"fallback",save:async()=>{saved++;persisted=JSON.parse(JSON.stringify([student]))},studentArchiveStore:{snapshot:async()=>persisted},lessonDraftStore:{load:async()=>({accountId:"synthetic-account",studentId:student.id,id:state.errorDraftLessonId,notes:fields.lessonNotes.value}),remove:async()=>{removed++;if(cleanupFails)throw Error("simulated")}},clearDrivingErrorDraft(){},openStudent:()=>{open++},alert:message=>alerts.push(message)});
 vm.runInContext(source.slice(source.indexOf("async function saveLesson()"),source.indexOf("async function deleteLesson",source.indexOf("async function saveLesson()"))),context);
 return{context,state,student,alerts,run:()=>context.saveLesson(),counts:()=>({saved,removed,open}),fields};
}
test("salvataggio definitivo congela i callback, verifica e non duplica su doppio tocco",async()=>{const f=fixture();const first=f.run();assert.equal(f.context.lessonDraftReady,false);await Promise.all([first,f.run()]);assert.equal(f.student.lessons.length,1);assert.deepEqual(f.counts(),{saved:1,removed:1,open:1});assert.equal(f.student.lessons[0].instructorName,"ISTRUTTORE FITTIZIO");assert.match(f.student.lessons[0].completedDraftSignature,/^[a-f0-9]{64}$/)});
test("pulizia fallita conserva guida verificata e identità: secondo salvataggio non duplica",async()=>{const f=fixture({cleanupFails:true});await f.run();assert.equal(f.student.lessons.length,1);assert.equal(f.context.lessonDraftReady,false);assert.match(f.alerts[0],/Guida salvata e verificata/);f.context.lessonDraftReady=true;await f.run();assert.equal(f.student.lessons.length,1)});
test("sessione non valida blocca una nuova guida prima di scrivere",async()=>{const f=fixture();f.context.window.AgendaAuth.currentUser=()=>null;await f.run();assert.deepEqual(f.counts(),{saved:0,removed:0,open:0});assert.equal(f.student.lessons.length,0)});
test("salvataggio reale conserva baseline, attività selezionate e fotografia cumulativa",async()=>{const f=fixture(),api=require("../lesson-activities.js");f.context.window.LessonActivities=api;f.context.lessonActivityDraft=api.begin([{id:"a",label:"ATTIVITÀ FITTIZIA",status:"repeat"},{id:"b",label:"ALTRA ATTIVITÀ",status:"good"}]);api.select(f.context.lessonActivityDraft,"a","orange");f.fields.lessonChecklist.dataset.items=JSON.stringify(f.context.lessonActivityDraft.snapshot);await f.run();assert.equal(f.student.lessons[0].lessonActivities.length,1);assert.equal(f.student.lessons[0].activitySnapshot.length,2);assert.equal(f.student.lessons[0].activityBaseline[0].status,"repeat");assert.equal(f.student.lessons[0].lessonActivities[0].status,"orange");});
test("impronta bozza include identità, note, punti e checklist, non il timer periodico",async()=>{const value={accountId:"a",studentId:"s",id:"l",notes:"TEST",route:[{lat:44,lng:8}],checklist:[],updatedAt:1};assert.equal(await Drafts.signature(value),await Drafts.signature({...value,updatedAt:2}));for(const change of [{accountId:"b"},{studentId:"b"},{notes:"CHANGED"},{route:[]},{checklist:["TEST"]}])assert.notEqual(await Drafts.signature(value),await Drafts.signature({...value,...change}))});
