"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm"),path=require("node:path");
const read=name=>fs.readFileSync(path.join(__dirname,"..",name),"utf8"),gps=require("../lesson-gps.js");
function extract(source,name){let start=source.indexOf(`  function ${name}(`);if(start<0)start=source.indexOf(`  async function ${name}(`);assert.ok(start>=0,name);return source.slice(start,source.indexOf("\n  }",start)+4);}
const point=(time,lat=44.4,lng=8.9,accuracy=5)=>({time,lat,lng,accuracy});
test("GPS urbano: jitter, partenza e svolta",()=>{const f=gps.create();assert.equal(f.observe(point(1000),0).accept,true);for(let i=2;i<15;i++){const v=f.observe(point(i*1000,44.4+(i%2)*.00001),0);assert.equal(v.accept,false);assert.equal(v.speed,0);}assert.equal(f.observe(point(16000,44.40012),4).accept,true);assert.equal(f.observe(point(20000,44.40012,8.9002),4).accept,true);});
test("GPS urbano: salto laterale, recupero confermato e nuovo segmento",()=>{const f=gps.create();f.observe(point(1000),0);f.observe(point(5000,44.4001),3);assert.equal(f.observe(point(6000,44.4001,8.901),3).accept,false);assert.equal(f.observe(point(10000,44.4002),3).accept,false);const p=f.observe(point(14000,44.4003),3);assert.equal(p.accept,true);assert.equal(p.breakBefore,true);assert.equal(f.observe(point(15000,44.4004,8.9,100),5).speed,null);});
test("report: oscillazione laterale esclusa, conferme e incertezza unica",()=>{const c=vm.createContext({});vm.runInContext(extract(read("r10-features.js"),"confirmedRoads"),c);const names=["A","A","Laterale","","","B","B"],out=c.confirmedRoads(names.map(()=>({})),names.map(name=>({name})));assert.deepEqual(Array.from(out),["A","Tratto con segnale GPS insufficiente","B"]);assert.equal(c.confirmedRoads([{},{breakBefore:true}],[{name:"A"},{name:"A"}]).length,1);});
test("backup: feedback immediato, doppio tocco, paint, successo ed errore",async()=>{let calls=0,paint,release;const messages=[],button={disabled:false,setAttribute(){},removeAttribute(){},classList:{add(){},remove(){}}};const c=vm.createContext({window:{setTimeout,requestAnimationFrame(fn){paint=fn}},clearTimeout,byId:()=>button,showMessage:s=>messages.push(s),createBackupPayload:()=>{calls++;return new Promise(r=>release=r)},createBackupFile:()=>({size:1}),formatBytes:()=>"1 B",BACKUP_EXTENSION:"json",presentPreparedBackup(){}});vm.runInContext('let exportInProgress=false;'+extract(read("full-backup.js"),"exportFullBackup"),c);const first=c.exportFullBackup();await c.exportFullBackup();assert.match(messages[0],/Preparazione/);assert.equal(button.disabled,true);assert.equal(calls,0);paint();await new Promise(r=>setTimeout(r,15));assert.equal(calls,1);release({metadata:{students:0,documents:0}});await first;assert.equal(button.disabled,false);assert.match(messages.at(-1),/Backup completo creato/);c.createBackupPayload=async()=>{throw Error("quota")};const failed=c.exportFullBackup();paint();await failed;assert.equal(button.disabled,false);assert.match(messages.at(-1),/dati sono invariati/);});
test("documenti: richiesta riuscita non equivale a commit, abort preservato",async()=>{let tx,request;const c=vm.createContext({STORE_NAME:"documents",openDatabase:async()=>({transaction(){return tx={objectStore(){return{};}}}})});vm.runInContext(extract(read("documents.js"),"runStore"),c);let resolved=false;const pending=c.runStore("readwrite",()=>request={result:"id"}).then(()=>resolved=true);await new Promise(setImmediate);request.onsuccess();await Promise.resolve();assert.equal(resolved,false);tx.oncomplete();await pending;assert.equal(resolved,true);const failed=c.runStore("readwrite",()=>request={result:"id"});await new Promise(setImmediate);request.onsuccess();tx.error=Error("quota sintetica");tx.onabort();await assert.rejects(failed,/quota/);});
test("documenti: rinomina fallita non muta record",async()=>{const record={id:"fittizio",title:"Prima",blob:{synthetic:true}},messages=[];const c=vm.createContext({requestDocumentTitle:async()=>"Dopo",putDocument:async()=>{throw Error("quota")},refreshDocuments:async()=>{},showMessage:s=>messages.push(s)});vm.runInContext(extract(read("documents.js"),"renameDocument"),c);await c.renameDocument(record);assert.equal(record.title,"Prima");assert.equal(record.blob.synthetic,true);assert.match(messages[0],/Non è stato possibile/);});
test("documenti: capacità fail-closed e operazioni simultanee",async()=>{let role=false,calls=0,release;const c=vm.createContext({window:{AgendaAuth:{can:()=>role}},showMessage(){}});vm.runInContext('let actionBusy=false;'+extract(read("documents.js"),"permitted")+extract(read("documents.js"),"guarded"),c);await c.guarded(()=>calls++);assert.equal(calls,0);role=true;const pending=c.guarded(()=>{calls++;return new Promise(r=>release=r)});await c.guarded(()=>calls++);assert.equal(calls,1);release();await pending;await c.guarded(()=>calls++);assert.equal(calls,2);});
test("documenti: formato video non genera stampa e download conserva link esplicito",()=>{let offered=0,clicked=0;const messages=[],c=vm.createContext({Date,offerDocument(){offered++},byId:()=>({querySelector:()=>({click(){clicked++}})}),showMessage:s=>messages.push(s)});vm.runInContext('let printBlockedUntil=0;'+extract(read("documents.js"),"printDocument")+extract(read("documents.js"),"downloadDocument"),c);c.printDocument({mimeType:"video/mp4"});assert.equal(offered,0);assert.match(messages[0],/non è stampabile/);c.downloadDocument({});assert.equal(offered,1);assert.equal(clicked,1);});
