"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),S=require("../student-archive-store.js");
test("bozze: eliminazione definitiva isolata per account e allievo, compensazione verificata",async()=>{
 const D=require("../lesson-drafts.js"),store=D.createStore({backend:D.memoryBackend()});
 for(const [accountId,studentId]of [["one","a"],["one","b"],["two","a"]])await store.save({id:`${accountId}-${studentId}`,accountId,studentId,startedAt:1,notes:"BOZZA FITTIZIA"});
 const before=await store.load("one","a"),undo=await store.removeStudents("one",["a"]);
 assert.equal(await store.load("one","a"),undefined);assert.ok(await store.load("one","b"));assert.ok(await store.load("two","a"));
 await undo();assert.deepEqual(await store.load("one","a"),before);
});
test("eliminazione definitiva: errore finale ripristina collegamenti bozze e patente, nuovo tentativo riesce",async()=>{
 const vm=require("node:vm"),fs=require("node:fs"),source=fs.readFileSync("app.js","utf8");let links=true,drafts=true,licenses=[{studentId:"a"}],trash=[{id:"a"}],fail=true;
 const context=vm.createContext({trashOperation:work=>work(),window:{StudentArchiveStore:S},studentArchiveStore:{snapshotTrash:async()=>structuredClone(trash),removeTrash:async()=>{if(fail)throw Error("quota sintetica");trash=[]}},studentLicenseStore:{snapshot:async()=>structuredClone(licenses),removeMany:async()=>{licenses=[]},replaceAll:async rows=>{licenses=rows}},removeStudentLinks:async()=>{links=false;return async()=>{links=true}},removeStudentDraftLinks:async()=>{drafts=false;return async()=>{drafts=true}}});
 vm.runInContext(source.slice(source.indexOf("async function purgeStudentTrash("),source.indexOf("async function purgeExpiredStudentTrash(")),context);
 await assert.rejects(context.purgeStudentTrash(["a"]),/quota/);assert.equal(links,true);assert.equal(drafts,true);assert.equal(licenses.length,1);assert.equal(trash.length,1);
 fail=false;await context.purgeStudentTrash(["a"]);assert.equal(links,false);assert.equal(drafts,false);assert.equal(licenses.length,0);assert.equal(trash.length,0);
});
async function fixture(){const records=[{id:"a",archived:true,lessons:[{id:"lesson",instructorId:"fake",instructorName:"ISTRUTTORE TEST",route:[]}],checklist:[]},{id:"b",lessons:[],checklist:[]}],backend=S.createMemoryBackend(),store=S.createStore({backend,legacyStorage:{getItem:()=>JSON.stringify(records)}});await store.initialize();return{records,backend,store}}
test("rimozione collegamenti conserva esami vuoti estranei e compensazione completa",async()=>{
 const vm=require("node:vm"),fs=require("node:fs"),source=fs.readFileSync("app.js","utf8"),copy=x=>JSON.parse(JSON.stringify(x));
 const exams=[{id:"empty",participants:[]},{id:"only",participants:[{studentId:"a"}]},{id:"shared",participants:[{studentId:"a"},{studentId:"b"}]}];
 let documents=[{id:"doc-a",studentId:"a"},{id:"doc-b",studentId:"b"}];const previous=copy(documents);
 const context=vm.createContext({state:{exams:copy(exams),examLocations:[]},examStore:{replaceAll:async items=>({exams:copy(items)})},openStudentDocumentDatabase:async()=>({close(){},transaction(){const tx={objectStore:()=>({getAll(){const req={};queueMicrotask(()=>{req.result=copy(documents);req.onsuccess();tx.oncomplete()});return req}})};return tx}}),restoreStudentImportDocuments:async(ids,rows)=>{documents=documents.filter(row=>!ids.includes(row.id)).concat(copy(rows))}});
 vm.runInContext(source.split(/\r?\n/).find(line=>line.startsWith("async function removeStudentLinks(ids)")),context);
 const undo=await context.removeStudentLinks(["a"]);
 assert.deepEqual(copy(context.state.exams),[exams[0],{id:"shared",participants:[{studentId:"b"}]}]);assert.deepEqual(documents,[previous[1]]);
 await undo();assert.deepEqual(copy(context.state.exams),exams);assert.deepEqual(documents.sort((a,b)=>a.id.localeCompare(b.id)),previous);
});
test("cestino: ID, stato e dati conservati per 15 giorni, ripristino senza duplicati",async()=>{const {records,store}=await fixture(),now=Date.UTC(2026,8,27);await store.moveToTrash(["a"],now);assert.deepEqual(await store.snapshot(),[records[1]]);const [entry]=await store.snapshotTrash();assert.deepEqual(entry.student,records[0]);assert.equal(S.trashExpired(entry,now+S.TRASH_MS-1),false);assert.equal(S.trashExpired(entry,now+S.TRASH_MS),true);await store.restoreTrash("a");assert.deepEqual((await store.snapshot()).find(s=>s.id==="a"),records[0]);assert.deepEqual(await store.snapshotTrash(),[]);await assert.rejects(store.restoreTrash("a"),/non presente/)});
test("cestino: quota e verifica fallita preservano l'archivio; nuovo tentativo riesce",async()=>{const {records,backend,store}=await fixture();backend.failNext(Object.assign(Error("quota sintetica"),{name:"QuotaExceededError"}));await assert.rejects(store.moveToTrash(["a"]),/quota/);assert.deepEqual(await store.snapshot(),records);assert.deepEqual(await store.snapshotTrash(),[]);await store.moveToTrash(["a"]);const before=await backend.snapshot();backend.failNext(Error("scrittura sintetica fallita"));await assert.rejects(store.restoreTrash("a"));assert.deepEqual(await backend.snapshot(),before);await store.restoreTrash("a");assert.equal((await store.snapshot()).length,2)});
test("cestino: backup e riapertura conservano dati e date; vecchio backup senza cestino",async()=>{const {store,backend}=await fixture();await store.moveToTrash(["a"]);const active=await store.snapshot(),trash=await store.snapshotTrash();const reopened=S.createStore({backend,legacyStorage:{getItem(){throw Error("non leggere la sorgente")}}});await reopened.initialize();assert.deepEqual(await reopened.snapshotTrash(),trash);await reopened.replaceArchive(active,trash);assert.deepEqual(await reopened.snapshotTrash(),trash);await assert.rejects(reopened.replaceArchive([trash[0].student],trash),/Conflitto/);assert.deepEqual(await reopened.snapshotTrash(),trash);await reopened.replaceArchive(active);assert.deepEqual(await reopened.snapshotTrash(),[])});
test("date del cestino malformate, future o durata alterata non causano scadenza automatica",()=>{const now=Date.UTC(2026,8,27);for(const entry of [{},{deletedAt:"invalid",purgeAfter:"invalid"},{deletedAt:new Date(now+1000).toISOString(),purgeAfter:new Date(now+1000+S.TRASH_MS).toISOString()},{deletedAt:new Date(now-1000).toISOString(),purgeAfter:new Date(now).toISOString()}])assert.equal(S.trashExpired(entry,now),false)});
test("importazione con ID nel cestino rifiutata senza modificare nessuna delle due raccolte",async()=>{const {store}=await fixture();await store.moveToTrash(["a"]);const active=await store.snapshot(),trash=await store.snapshotTrash();await assert.rejects(store.replaceAll([...active,{id:"a",firstName:"ALTRO DATO FITTIZIO"}]),/nel cestino/);assert.deepEqual(await store.snapshot(),active);assert.deepEqual(await store.snapshotTrash(),trash)});
