"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),api=require("../student-license-store.js");
const license=(number="AB 123")=>({number,issueDate:"2026-09-14",expiryDate:"2036-09-14"});

test("migra una patente incorporata, la verifica e non muta la sorgente storica",async()=>{const backend=api.createMemoryBackend(),store=api.createStore({backend}),students=[{id:"s1",drivingLicense:license()}],source=JSON.stringify(students);await store.initialize(students);assert.equal(JSON.stringify(students),source);assert.deepEqual(await store.snapshot(),[{studentId:"s1",...license()}]);assert.equal((await store.migrationStatus()).status,"verified")});
test("archivio realmente assente viene inizializzato vuoto",async()=>{const store=api.createStore({backend:api.createMemoryBackend()});await store.initialize([{id:"s1"}]);assert.deepEqual(await store.snapshot(),[])});
test("dato storico malformato blocca la migrazione senza creare un falso archivio vuoto",async()=>{const backend=api.createMemoryBackend(),store=api.createStore({backend});await assert.rejects(store.initialize([{id:"s1",drivingLicense:{number:"AA"}}]),/Completa/);assert.deepEqual(await backend.getAll(),[]);assert.equal(await backend.meta(),null)});
test("dopo migrazione verificata IndexedDB prevale sulla fotografia incorporata",async()=>{const backend=api.createMemoryBackend(),first=api.createStore({backend});await first.initialize([{id:"s1",drivingLicense:license("NUOVA")}]);const second=api.createStore({backend});await second.initialize([{id:"s1",drivingLicense:license("VECCHIA")}]);assert.equal((await second.get("s1")).number,"NUOVA")});
test("salva un solo record e una scrittura fallita conserva il precedente",async()=>{const backend=api.createMemoryBackend(),store=api.createStore({backend});await store.initialize([]);await store.save("s1",license("PRIMA"));const quota=Object.assign(Error("quota"),{name:"QuotaExceededError"});backend.setFailure(quota);await assert.rejects(store.save("s1",license("DOPO")),/Spazio locale insufficiente/);assert.equal((await store.get("s1")).number,"PRIMA")});
test("attachStudents idrata senza alterare l'array originale",async()=>{const store=api.createStore({backend:api.createMemoryBackend()}),students=[{id:"s1",firstName:"Anna"}];await store.initialize([]);await store.save("s1",license());const hydrated=await store.attachStudents(students);assert.equal(students[0].drivingLicense,undefined);assert.deepEqual(hydrated[0].drivingLicense,license())});
test("replaceAll è canonico e ripristina lo snapshot se la scrittura fallisce",async()=>{const backend=api.createMemoryBackend(),store=api.createStore({backend});await store.initialize([]);await store.replaceAll([{studentId:"b",...license("B")},{studentId:"a",...license("A")}]);assert.deepEqual((await store.snapshot()).map(x=>x.studentId),["a","b"]);backend.setFailure(Error("guasto"));await assert.rejects(store.replaceAll([{studentId:"c",...license("C")}]),/guasto/);assert.deepEqual((await store.snapshot()).map(x=>x.studentId),["a","b"])});
test("rimozione multipla elimina solo gli ID richiesti",async()=>{const store=api.createStore({backend:api.createMemoryBackend()});await store.initialize([]);await store.replaceAll([{studentId:"a",...license("A")},{studentId:"b",...license("B")}]);await store.removeMany(["a"]);assert.deepEqual((await store.snapshot()).map(x=>x.studentId),["b"])});
test("archivi distinti restano isolati",async()=>{const one=api.createStore({backend:api.createMemoryBackend()}),two=api.createStore({backend:api.createMemoryBackend()});await one.initialize([]);await two.initialize([]);await one.save("s1",license());assert.equal(await two.get("s1"),null)});
test("migrazione interrotta riprende dagli stessi dati senza duplicazioni",async()=>{const base=api.createMemoryBackend();let puts=0,fail=true;const backend={...base,async put(value){puts++;if(fail&&puts===2){fail=false;throw Error("interrotto")}return base.put(value)}};const students=[{id:"a",drivingLicense:license("A")},{id:"b",drivingLicense:license("B")}];await assert.rejects(api.createStore({backend}).initialize(students),/interrotto/);assert.equal(await base.meta(),null);const resumed=api.createStore({backend});await resumed.initialize(students);assert.deepEqual((await resumed.snapshot()).map(item=>item.studentId),["a","b"]);assert.equal((await resumed.migrationStatus()).status,"verified")});
test("riconciliazione al riavvio elimina soltanto patenti orfane",async()=>{const store=api.createStore({backend:api.createMemoryBackend()});await store.initialize([]);await store.replaceAll([{studentId:"presente",...license("A")},{studentId:"eliminato",...license("B")}]);await store.reconcile(["presente"]);assert.deepEqual((await store.snapshot()).map(item=>item.studentId),["presente"])});
