"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto"),http=require("node:http"),os=require("node:os"),{spawn}=require("node:child_process");
const {DatabaseSync}=require("node:sqlite"),root=path.resolve(__dirname,"..");
async function worker(){const source=fs.readFileSync(path.join(root,"worker.js"),"utf8");return import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`)}
function password(password,salt="c2FsdC1maXR0aXppbyE="){return crypto.pbkdf2Sync(password,Buffer.from(salt,"base64"),100000,32,"sha256").toString("base64")}
function rows(db,table,columns="*"){return db.prepare(`SELECT ${columns} FROM ${table} ORDER BY 1`).all().map(row=>({...row}))}
function insertUser(db,id,username,role,active=1){const salt="c2FsdC1maXR0aXppbyE=";db.prepare(`INSERT INTO users(id,username,name,role,password_hash,password_salt,password_iterations,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,username,username.toUpperCase(),role,password("PasswordFittizia!",salt),salt,100000,active,"2026-08-31T00:00:00Z","2026-08-31T00:00:00Z")}
test("migrazione additiva preserva integralmente record ID relazioni e autenticazione",async()=>{
 const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON");db.exec(fs.readFileSync(path.join(root,"migrations","0001_auth.sql"),"utf8"));
 insertUser(db,"admin-id","admin","ADMIN");insertUser(db,"active-id","active","ISTRUTTORE");insertUser(db,"blocked-id","blocked","ISTRUTTORE",0);
 db.prepare("INSERT INTO sessions(id_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)").run("valid","active-id","2099-01-01","2026-01-01");db.prepare("INSERT INTO sessions(id_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)").run("expired","blocked-id","2020-01-01","2019-01-01");
 db.exec(fs.readFileSync(path.join(root,"migrations","0002_user_employment_periods.sql"),"utf8"));
 const cols="id,username,name,role,password_hash,password_salt,password_iterations,active,created_at,updated_at",before={users:rows(db,"users",cols),sessions:rows(db,"sessions","id_hash,user_id,expires_at,created_at"),periods:rows(db,"user_employment_periods"),namespaces:rows(db,"users","id").map(x=>`agenda-register-account:${x.id}`)};
 db.exec(fs.readFileSync(path.join(root,"migrations","0003_user_manager_and_temporary_passwords.sql"),"utf8"));
 const after={users:rows(db,"users",cols),sessions:rows(db,"sessions","id_hash,user_id,expires_at,created_at"),periods:rows(db,"user_employment_periods"),namespaces:rows(db,"users","id").map(x=>`agenda-register-account:${x.id}`)};
 assert.deepEqual(after,before);assert.deepEqual(rows(db,"users","authorization_role,is_primary_admin,must_change_password,session_version"),Array(3).fill(null).map(()=>({authorization_role:null,is_primary_admin:0,must_change_password:0,session_version:1})));
 assert.deepEqual(rows(db,"sessions","session_version,purpose"),Array(2).fill(null).map(()=>({session_version:1,purpose:"NORMAL"})));assert.deepEqual(db.prepare("PRAGMA foreign_key_check").all(),[]);
 const {verifyPassword}=await worker();for(const user of db.prepare("SELECT * FROM users").all())assert.equal(await verifyPassword("PasswordFittizia!",user),true);
 const legacyRead=db.prepare("SELECT u.id,u.role,u.password_hash,u.password_salt,u.active,s.id_hash FROM sessions s JOIN users u ON u.id=s.user_id ORDER BY s.id_hash").all().map(row=>({...row}));assert.equal(legacyRead.length,2);assert.equal(legacyRead.every(row=>before.users.some(user=>user.id===row.id&&user.role===row.role&&user.password_hash===row.password_hash&&user.password_salt===row.password_salt&&user.active===row.active)),true);
 assert.throws(()=>db.exec(fs.readFileSync(path.join(root,"migrations","0003_user_manager_and_temporary_passwords.sql"),"utf8")),/duplicate column/i);assert.deepEqual({users:rows(db,"users",cols),sessions:rows(db,"sessions","id_hash,user_id,expires_at,created_at"),periods:rows(db,"user_employment_periods"),namespaces:rows(db,"users","id").map(x=>`agenda-register-account:${x.id}`)},before);db.close();
});
test("migrazione 0004 conserva identità e relazioni e fotografa l'Audit esistente",()=>{
 const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON");for(const migration of ["0001_auth.sql","0002_user_employment_periods.sql","0003_user_manager_and_temporary_passwords.sql"])db.exec(fs.readFileSync(path.join(root,"migrations",migration),"utf8"));
 insertUser(db,"admin-id","admin","ADMIN");insertUser(db,"target-id","gestore","ISTRUTTORE");db.prepare("INSERT INTO sessions(id_hash,user_id,expires_at,created_at,session_version,purpose) VALUES(?,?,?,?,?,?)").run("session","admin-id","2099-01-01","2026-01-01",1,"NORMAL");db.prepare("INSERT INTO user_employment_periods(id,user_id,employment_type,effective_from,created_at,created_by) VALUES(?,?,?,?,?,?)").run("period","target-id","PART_TIME","2026-08-31","2026-01-01","admin-id");db.prepare("INSERT INTO user_management_audit(id,occurred_at,actor_user_id,target_user_id,action,outcome,reason_code,request_id) VALUES(?,?,?,?,?,?,?,?)").run("audit","2026-09-01","admin-id","target-id","CREATE_USER","SUCCESS","CREATED","request");
 const before={users:rows(db,"users"),sessions:rows(db,"sessions"),periods:rows(db,"user_employment_periods")};db.exec(fs.readFileSync(path.join(root,"migrations","0004_persistent_user_management_audit.sql"),"utf8"));
 assert.deepEqual({users:rows(db,"users"),sessions:rows(db,"sessions"),periods:rows(db,"user_employment_periods")},before);assert.deepEqual(db.prepare("PRAGMA foreign_key_check").all(),[]);const snapshot={actor_user_ref:"admin-id",actor_username:"admin",actor_name:"ADMIN",target_user_ref:"target-id",target_username:"gestore",target_name:"GESTORE"};assert.deepEqual({...db.prepare("SELECT actor_user_ref,actor_username,actor_name,target_user_ref,target_username,target_name FROM user_management_audit WHERE id='audit'").get()},snapshot);db.exec("DELETE FROM sessions; DELETE FROM user_employment_periods; DELETE FROM users;");assert.deepEqual({...db.prepare("SELECT actor_user_ref,actor_username,actor_name,target_user_ref,target_username,target_name FROM user_management_audit WHERE id='audit'").get()},snapshot);assert.deepEqual(db.prepare("PRAGMA foreign_key_check").all(),[]);db.close();
});
test("ruoli e capacità applicano il minimo privilegio",async()=>{const {effectiveRole,capabilitiesFor,requireUserManager,manageableTarget}=await worker();const primary={id:"p",role:"ADMIN",is_primary_admin:1},admin={id:"a",role:"ADMIN"},manager={id:"m",role:"ISTRUTTORE",authorization_role:"USER_MANAGER"},normal={id:"u",role:"ISTRUTTORE"};assert.equal(effectiveRole(manager),"USER_MANAGER");assert.equal(capabilitiesFor(manager).useApplication,false);assert.equal(requireUserManager(manager),null);assert.equal(manageableTarget(manager,normal),true);assert.equal(manageableTarget(manager,admin),false);assert.equal(manageableTarget(primary,admin),true);assert.equal(manageableTarget(primary,primary),false)});
test("combinazioni incoerenti dei ruoli falliscono in modo chiuso",async()=>{const {effectiveRole,capabilitiesFor,requireUserManager}=await worker();for(const row of [{role:"ADMIN",authorization_role:"ISTRUTTORE"},{role:"ISTRUTTORE",authorization_role:"ADMIN"},{role:"ADMIN",authorization_role:"USER_MANAGER"},{role:"ADMIN",authorization_role:"ROOT"},{role:"ROOT",authorization_role:null}]){assert.equal(effectiveRole(row),null);assert.deepEqual(capabilitiesFor(row),{useApplication:false,manageUsers:false,managePrivilegedUsers:false,viewAudit:false});assert.notEqual(requireUserManager(row),null)}assert.equal(effectiveRole({role:"ADMIN",authorization_role:null}),"ADMIN");assert.equal(effectiveRole({role:"ISTRUTTORE",authorization_role:null}),"ISTRUTTORE")});
test("il flag del principale accetta soltanto uno numerico o serializzato",async()=>{const {primaryAdminFlag,capabilitiesFor}=await worker();for(const value of [0,"0",false,true,null,undefined,"",2,"1x"," 1"]){assert.equal(primaryAdminFlag({is_primary_admin:value}),false);assert.equal(capabilitiesFor({role:"ADMIN",authorization_role:"ADMIN",is_primary_admin:value}).viewAudit,false)}assert.equal(primaryAdminFlag({is_primary_admin:1}),true);assert.equal(primaryAdminFlag({is_primary_admin:"1"}),true)});
test("principale, privilegiati e ultimo ADMIN sono protetti lato server",()=>{const source=fs.readFileSync(path.join(root,"worker.js"),"utf8");assert.match(source,/target\.is_primary_admin/);assert.match(source,/ultimo amministratore abilitato/);assert.match(source,/manageableTarget\(actor, target\)/);assert.match(source,/Configura e utilizza l’amministratore principale/);assert.match(source,/Funzione riservata all’amministratore principale/);assert.match(source,/LIMIT \?/)});
test("whitelist rigida blocca ruolo contraffatto e mass assignment",async()=>{const {strictBody}=await worker();const allowed=["name","username","employmentType","employmentEffectiveFrom","operatorPassword"];assert.equal(strictBody({name:"Mario",role:"ADMIN"},allowed),false);assert.equal(strictBody({name:"Mario",session_version:99},allowed),false);assert.equal(strictBody({name:"Mario",is_primary_admin:true},allowed),false);assert.equal(strictBody({name:"Mario"},allowed),true)});
test("password provvisoria è robusta e non coincide con un PIN",async()=>{const {randomTemporaryPassword}=await worker();const values=new Set(Array.from({length:20},()=>randomTemporaryPassword()));assert.equal(values.size,20);for(const value of values){assert.equal(value.length,20);assert.doesNotMatch(value,/^\d{4}$/)}});
test("Origin è obbligatoria e strettamente uguale",async()=>{const {sameOrigin}=await worker();assert.equal(sameOrigin(new Request("https://agenda.test/api",{method:"POST"})),false);assert.equal(sameOrigin(new Request("https://agenda.test/api",{method:"POST",headers:{origin:"https://evil.test"}})),false);assert.equal(sameOrigin(new Request("https://agenda.test/api",{method:"POST",headers:{origin:"https://agenda.test"}})),true)});
test("rotte ristrette, consumo atomico e sessione limitata sono presenti",()=>{const source=fs.readFileSync(path.join(root,"worker.js"),"utf8");for(const route of ["/api/user-management/users","/status","/temporary-password"])assert.match(source,new RegExp(route.replaceAll("/","\\/")));assert.match(source,/temporary_password_used_at IS NULL AND temporary_password_expires_at>/);assert.match(source,/purpose === "PASSWORD_CHANGE"/);assert.match(source,/DELETE FROM sessions WHERE user_id=\?/);assert.match(source,/session_version=session_version\+1/);assert.match(source,/COALESCE\(u\.authorization_role,u\.role\)='ISTRUTTORE'/)});
test("audit e throttling non contengono segreti",()=>{const sql=fs.readFileSync(path.join(root,"migrations","0003_user_manager_and_temporary_passwords.sql"),"utf8");const audit=sql.slice(sql.indexOf("CREATE TABLE user_management_audit"),sql.indexOf("CREATE INDEX user_management_audit"));assert.doesNotMatch(audit,/password|token|cookie|pin|recovery|salt|hash/i);assert.match(sql,/CREATE TABLE security_throttles/);assert.match(sql,/key_hash/)});
test("reset generale permanente è rifiutato a favore della password provvisoria",()=>{const source=fs.readFileSync(path.join(root,"worker.js"),"utf8");assert.match(source,/Usa la funzione Password provvisoria/);assert.doesNotMatch(source,/updates\.push\("password_hash=\?"/);assert.match(source,/\/api\/user-management\/audit/)});
test("USER_MANAGER usa solo shell gestionale e non carica i moduli operativi",()=>{const client=fs.readFileSync(path.join(root,"auth-client.js"),"utf8");assert.match(client,/if \(currentUser\?\.role === "USER_MANAGER"\) return showManagerShell\(\)/);assert.match(client,/routeAfterAuthentication/);assert.match(client,/\/api\/user-management\/users/);assert.match(client,/document\.querySelectorAll\("#appShell \.view"\)/);assert.match(client,/managerLogout/);assert.match(client,/capabilities\?\.viewAudit/);assert.match(client,/temporaryPasswordValue.*textContent = ""/);assert.match(client,/Impossibile leggere lo storico Audit/);assert.match(client,/target_name \|\| event\.target_username \|\| event\.target_user_ref/)});
test("il markup iniziale non contiene il pannello audit",()=>{assert.doesNotMatch(fs.readFileSync(path.join(root,"index.html"),"utf8"),/id="userManagementAudit"|id="refreshUserAudit"|id="userAuditList"/)});
test("la migrazione non usa DDL o DML distruttivo e non rimappa record",()=>{const sql=fs.readFileSync(path.join(root,"migrations","0003_user_manager_and_temporary_passwords.sql"),"utf8").replace(/^--.*$/gm,"").replace(/ON DELETE SET NULL/gi,"");assert.doesNotMatch(sql,/\b(?:DROP|UPDATE|INSERT|SELECT|DELETE)\b/i);assert.match(sql,/ALTER TABLE users ADD COLUMN/);assert.match(sql,/ALTER TABLE sessions ADD COLUMN/)});

const edgePath="C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe";
function runEdge(url,profile){
 return new Promise((resolve,reject)=>{
   const child=spawn(edgePath,["--headless=new","--disable-gpu","--disable-software-rasterizer","--use-gl=disabled","--disable-features=VizDisplayCompositor","--disable-background-networking","--disable-component-update","--no-first-run","--no-default-browser-check",`--user-data-dir=${profile}`,"--dump-dom","--virtual-time-budget=1400",url],{windowsHide:true});
  let stdout="",stderr="";child.stdout.on("data",chunk=>stdout+=chunk);child.stderr.on("data",chunk=>stderr+=chunk);
   const timer=setTimeout(()=>{child.kill();reject(new Error("Timeout del browser reale locale."))},60000);
  child.on("error",reject);child.on("close",code=>{clearTimeout(timer);code===0?resolve(stdout):reject(new Error(`Edge headless ${code}: ${stderr}`))});
 });
}
async function removeBrowserProfile(profile){let lastError;for(let attempt=0;attempt<20;attempt++){try{fs.rmSync(profile,{recursive:true,force:true,maxRetries:2,retryDelay:100});return}catch(error){lastError=error;await new Promise(resolve=>setTimeout(resolve,150))}}throw lastError}
test("browser reale: Audit esiste solo per il principale e nessun altro account lo richiede",{timeout:300000},async t=>{
 if(!fs.existsSync(edgePath)){t.skip("Microsoft Edge non disponibile");return}
 const sourceIndex=fs.readFileSync(path.join(root,"index.html"),"utf8"),sourceClient=fs.readFileSync(path.join(root,"auth-client.js"),"utf8");
 const injection=`<output id="browserAuditRequestCount">0</output><script>
  (()=>{const kind=new URLSearchParams(location.search).get("identity");const identities={
   primary:{id:"p",name:"PRINCIPALE",username:"primary",role:"ADMIN",capabilities:{useApplication:true,manageUsers:true,managePrivilegedUsers:true,viewAudit:true}},
   admin:{id:"a",name:"ADMIN SECONDARIO",username:"admin",role:"ADMIN",capabilities:{useApplication:true,manageUsers:true,managePrivilegedUsers:false,viewAudit:false}},
   manager:{id:"m",name:"GESTORE",username:"manager",role:"USER_MANAGER",capabilities:{useApplication:false,manageUsers:true,managePrivilegedUsers:false,viewAudit:false}},
   instructor:{id:"i",name:"ISTRUTTORE",username:"instructor",role:"ISTRUTTORE",capabilities:{useApplication:true,manageUsers:false,managePrivilegedUsers:false,viewAudit:false}}
  };window.__auditRequests=0;const nativeFetch=window.fetch.bind(window);
  window.fetch=async(input,options)=>{const target=new URL(typeof input==="string"?input:input.url,location.href);
   if(target.pathname==="/api/auth/me")return new Response(JSON.stringify({user:identities[kind]}),{status:200,headers:{"content-type":"application/json"}});
   if(target.pathname==="/api/user-management/users"||target.pathname==="/api/users")return new Response(JSON.stringify({users:[]}),{status:200,headers:{"content-type":"application/json"}});
   if(target.pathname==="/api/user-management/audit"){window.__auditRequests++;document.getElementById("browserAuditRequestCount").textContent=String(window.__auditRequests);return new Response(JSON.stringify({events:[]}),{status:200,headers:{"content-type":"application/json"}})}
   return nativeFetch(input,options);
  };
  addEventListener("DOMContentLoaded",()=>setTimeout(()=>{if(kind==="primary")document.getElementById("refreshUserAudit")?.click()},350));
  })();
 </script>`;
 const fixture=sourceIndex.replace('<script src="auth-client.js?v=5"></script>',injection+'<script src="/auth-client.js"></script>');
 const server=http.createServer((request,response)=>{const pathname=new URL(request.url,"http://local").pathname;if(pathname==="/"){response.setHeader("content-type","text/html; charset=utf-8");response.end(fixture)}else if(pathname==="/auth-client.js"){response.setHeader("content-type","text/javascript");response.end(sourceClient)}else if(pathname.endsWith(".js")){response.setHeader("content-type","text/javascript");response.end("window.AgendaAppReady=Promise.resolve();")}else{response.statusCode=204;response.end()}});
 await new Promise(resolve=>server.listen(0,"127.0.0.1",resolve));const port=server.address().port;
 try{
  for(const identity of ["primary","admin","manager","instructor"]){const profile=fs.mkdtempSync(path.join(os.tmpdir(),`agenda-audit-${identity}-`));try{const dom=await runEdge(`http://127.0.0.1:${port}/?identity=${identity}`,profile);const authorized=identity==="primary";assert.equal(/id="userManagementAudit"/.test(dom),authorized,`${identity}: presenza pannello`);assert.equal(/id="refreshUserAudit"/.test(dom),authorized,`${identity}: presenza comando`);assert.match(dom,new RegExp(`id="browserAuditRequestCount">${authorized?1:0}<`),`${identity}: richieste audit`)}finally{await removeBrowserProfile(profile)}}
 }finally{await new Promise(resolve=>server.close(resolve))}
});

class LocalD1 {
 constructor(db){this.db=db}
 prepare(sql){return new LocalStatement(this.db,sql)}
 async batch(statements){this.db.exec("BEGIN");try{const out=[];for(const statement of statements)out.push(await statement.run());this.db.exec("COMMIT");return out}catch(error){this.db.exec("ROLLBACK");throw error}}
}
class LocalStatement {
 constructor(db,sql,args=[]){this.db=db;this.sql=sql;this.args=args}
 bind(...args){return new LocalStatement(this.db,this.sql,args)}
 async first(){return this.db.prepare(this.sql).get(...this.args)||null}
 async all(){return {results:this.db.prepare(this.sql).all(...this.args).map(row=>({...row}))}}
 async run(){const result=this.db.prepare(this.sql).run(...this.args);return {success:true,meta:{changes:Number(result.changes||0)}}}
}
function seedSecuredUser(db,{id,username,role="ISTRUTTORE",authorizationRole=role,primary=0,active=1,passwordText="PasswordFittizia!"}){const salt="c2FsdC1maXR0aXppbyE=",now="2026-09-14T08:00:00Z";db.prepare(`INSERT INTO users(id,username,name,role,authorization_role,is_primary_admin,password_hash,password_salt,password_iterations,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,username,username.toUpperCase(),role,authorizationRole,primary,password(passwordText,salt),salt,100000,active,now,now);db.prepare("INSERT INTO user_employment_periods(id,user_id,employment_type,effective_from,created_at,created_by) VALUES(?,?,?,?,?,?)").run(`period-${id}`,id,"PART_TIME","2026-08-31",now,id)}
function apiRequest(pathname,{method="GET",body,cookie,origin="https://agenda.test"}={}){const headers={};if(origin!==null)headers.origin=origin;if(cookie)headers.cookie=cookie;if(body!==undefined)headers["content-type"]="application/json";return new Request(`https://agenda.test${pathname}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)})}
function cookieOf(response){return String(response.headers.get("set-cookie")||"").split(";")[0]}
async function responseJson(response){return {status:response.status,body:await response.json(),cookie:cookieOf(response)}}
test("flusso HTTP locale USER_MANAGER, password provvisoria e attacchi restano confinati",async()=>{
 const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON");for(const migration of ["0001_auth.sql","0002_user_employment_periods.sql","0003_user_manager_and_temporary_passwords.sql","0004_persistent_user_management_audit.sql"])db.exec(fs.readFileSync(path.join(root,"migrations",migration),"utf8"));
 seedSecuredUser(db,{id:"primary",username:"primary",role:"ADMIN",authorizationRole:"ADMIN",primary:1});
 seedSecuredUser(db,{id:"admin",username:"admin2",role:"ADMIN",authorizationRole:"ADMIN"});
 seedSecuredUser(db,{id:"manager",username:"manager",authorizationRole:"USER_MANAGER"});
 seedSecuredUser(db,{id:"active",username:"active"});
 seedSecuredUser(db,{id:"blocked",username:"blocked",active:0});
 const module=await worker(),env={DB:new LocalD1(db),ASSETS:{fetch:async()=>new Response("asset")}};
 const call=(path,options)=>module.default.fetch(apiRequest(path,options),env);
 const managerLogin=await responseJson(await call("/api/auth/login",{method:"POST",body:{username:"manager",password:"PasswordFittizia!"}}));assert.equal(managerLogin.status,200);const managerCookie=managerLogin.cookie;
 const list=await responseJson(await call("/api/user-management/users",{cookie:managerCookie}));assert.equal(list.status,200);assert.deepEqual(list.body.users.map(x=>x.id).sort(),["active","blocked"]);assert.equal(list.body.users.some(x=>x.role!=="ISTRUTTORE"),false);
 assert.equal((await call("/api/users",{cookie:managerCookie})).status,403);
 assert.equal((await call("/api/user-management/users",{method:"POST",cookie:managerCookie,body:{name:"Attacco",username:"attacco",role:"ADMIN",employmentType:"PART_TIME",employmentEffectiveFrom:"2026-09-14",operatorPassword:"PasswordFittizia!"}})).status,400);
 const created=await responseJson(await call("/api/user-management/users",{method:"POST",cookie:managerCookie,body:{name:"Nuovo Utente",username:"nuovo",employmentType:"PART_TIME",employmentEffectiveFrom:"2026-09-14",operatorPassword:"PasswordFittizia!"}}));assert.equal(created.status,201);assert.equal(created.body.user.role,"ISTRUTTORE");assert.equal(typeof created.body.temporaryPassword,"string");
 assert.equal((await call(`/api/user-management/users/${created.body.user.id}/status`,{method:"POST",cookie:managerCookie,body:{active:false}})).status,200);assert.equal(db.prepare("SELECT active FROM users WHERE id=?").get(created.body.user.id).active,0);
 assert.equal((await call(`/api/user-management/users/${created.body.user.id}/status`,{method:"POST",cookie:managerCookie,body:{active:true}})).status,200);
 assert.equal((await call("/api/user-management/users/admin/temporary-password",{method:"POST",cookie:managerCookie,body:{operatorPassword:"PasswordFittizia!"}})).status,404);
 const activeLogin=await responseJson(await call("/api/auth/login",{method:"POST",body:{username:"active",password:"PasswordFittizia!"}}));assert.equal(activeLogin.status,200);
 const issued=await responseJson(await call("/api/user-management/users/active/temporary-password",{method:"POST",cookie:managerCookie,body:{operatorPassword:"PasswordFittizia!"}}));assert.equal(issued.status,200);assert.equal((await call("/api/auth/me",{cookie:activeLogin.cookie})).status,401);
 const [temporaryA,temporaryB]=await Promise.all([call("/api/auth/login",{method:"POST",body:{username:"active",password:issued.body.temporaryPassword}}),call("/api/auth/login",{method:"POST",body:{username:"active",password:issued.body.temporaryPassword}})]);assert.deepEqual([temporaryA.status,temporaryB.status].sort(),[200,401]);const passwordCookie=temporaryA.status===200?cookieOf(temporaryA):cookieOf(temporaryB);
 assert.equal((await call("/api/auth/me",{cookie:passwordCookie})).status,200);assert.equal((await call("/app.js",{cookie:passwordCookie})).status,403);assert.equal((await call("/api/account/employment",{cookie:passwordCookie})).status,403);
 assert.equal((await call("/api/auth/password",{method:"POST",cookie:passwordCookie,body:{currentPassword:"",newPassword:"PasswordPersonaleNuova!",confirmPassword:"PasswordPersonaleNuova!"}})).status,200);
 assert.equal((await call("/api/auth/login",{method:"POST",body:{username:"active",password:issued.body.temporaryPassword}})).status,401);const normalAgain=await responseJson(await call("/api/auth/login",{method:"POST",body:{username:"active",password:"PasswordPersonaleNuova!"}}));assert.equal(normalAgain.status,200);
 assert.equal((await call("/api/user-management/audit",{cookie:normalAgain.cookie})).status,403);
 db.prepare("UPDATE users SET session_version=session_version+1 WHERE id='active'").run();assert.equal((await call("/api/auth/me",{cookie:normalAgain.cookie})).status,401);
 const expired=await responseJson(await call("/api/user-management/users/active/temporary-password",{method:"POST",cookie:managerCookie,body:{operatorPassword:"PasswordFittizia!"}}));assert.equal(expired.status,200);db.prepare("UPDATE users SET temporary_password_expires_at='2020-01-01T00:00:00Z' WHERE id='active'").run();assert.equal((await call("/api/auth/login",{method:"POST",body:{username:"active",password:expired.body.temporaryPassword}})).status,401);
 assert.equal((await call("/api/user-management/users",{method:"POST",cookie:managerCookie,origin:null,body:{}})).status,403);assert.equal((await call("/api/user-management/users",{method:"POST",cookie:managerCookie,origin:"https://evil.test",body:{}})).status,403);
 for(let i=0;i<5;i++)await call("/api/auth/login",{method:"POST",body:{username:"inesistente",password:"errata"}});
 assert.equal((await call("/api/auth/login",{method:"POST",body:{username:"inesistente",password:"errata"}})).status,429);
 for(let i=0;i<5;i++)await call("/api/user-management/users/active/temporary-password",{method:"POST",cookie:managerCookie,body:{operatorPassword:"errata"}});
 assert.equal((await call("/api/user-management/users/active/temporary-password",{method:"POST",cookie:managerCookie,body:{operatorPassword:"errata"}})).status,429);
 const auditRows=db.prepare("SELECT * FROM user_management_audit").all();assert.ok(auditRows.length>0);assert.doesNotMatch(JSON.stringify(auditRows),/PasswordFittizia|PasswordPersonaleNuova|agenda_session|password_hash|password_salt/);
 assert.equal((await call("/api/user-management/audit",{cookie:managerCookie})).status,403);
 const adminLogin=await responseJson(await call("/api/auth/login",{method:"POST",body:{username:"admin2",password:"PasswordFittizia!"}}));assert.equal((await call("/api/user-management/audit",{cookie:adminLogin.cookie})).status,403);
 const primaryLogin=await responseJson(await call("/api/auth/login",{method:"POST",body:{username:"primary",password:"PasswordFittizia!"}}));assert.equal((await call("/api/user-management/audit",{cookie:primaryLogin.cookie})).status,200);
 const managed=await responseJson(await call("/api/users",{method:"POST",cookie:primaryLogin.cookie,body:{name:"GESTORE COLLAUDO",username:"gestore.audit",password:"PasswordFittizia!",role:"USER_MANAGER",employmentType:"PART_TIME",employmentEffectiveFrom:"2026-09-14"}}));assert.equal(managed.status,201);
 assert.equal((await call(`/api/users/${managed.body.user.id}`,{method:"PATCH",cookie:primaryLogin.cookie,body:{active:false}})).status,200);assert.equal((await call(`/api/users/${managed.body.user.id}`,{method:"PATCH",cookie:primaryLogin.cookie,body:{active:true}})).status,200);assert.equal((await call(`/api/users/${managed.body.user.id}`,{method:"DELETE",cookie:primaryLogin.cookie})).status,200);
 const persisted=db.prepare("SELECT action,target_user_id,target_user_ref,target_username,target_name FROM user_management_audit WHERE target_user_ref=? ORDER BY occurred_at,id").all(managed.body.user.id).map(row=>({...row}));assert.deepEqual(persisted.map(row=>row.action).sort(),["BLOCK_USER","CREATE_USER_MANAGER","DELETE_USER","ENABLE_USER"]);assert.equal(persisted.every(row=>row.target_user_id===null&&row.target_user_ref===managed.body.user.id&&row.target_username==="gestore.audit"&&row.target_name==="GESTORE COLLAUDO"),true);
 const oldDate=new Date(Date.now()-181*24*60*60*1000).toISOString(),recentDate=new Date(Date.now()-10*24*60*60*1000).toISOString();db.prepare("INSERT INTO user_management_audit(id,occurred_at,action,outcome,reason_code,request_id,target_user_ref) VALUES(?,?,?,?,?,?,?)").run("old-event",oldDate,"TEST","SUCCESS","OLD","old","old");db.prepare("INSERT INTO user_management_audit(id,occurred_at,action,outcome,reason_code,request_id,target_user_ref) VALUES(?,?,?,?,?,?,?)").run("recent-event",recentDate,"TEST","SUCCESS","RECENT","recent","recent");assert.equal((await call("/api/users/active",{method:"PATCH",cookie:primaryLogin.cookie,body:{name:"ACTIVE RINOMINATO"}})).status,200);assert.equal(db.prepare("SELECT COUNT(*) total FROM user_management_audit WHERE id='old-event'").get().total,0);assert.equal(db.prepare("SELECT COUNT(*) total FROM user_management_audit WHERE id='recent-event'").get().total,1);
 const restarted=await worker(),restartCall=(path,options)=>restarted.default.fetch(apiRequest(path,options),env),afterRestart=await responseJson(await restartCall("/api/user-management/audit",{cookie:primaryLogin.cookie}));assert.equal(afterRestart.status,200);assert.equal(afterRestart.body.events.some(event=>event.action==="DELETE_USER"&&event.target_user_ref===managed.body.user.id),true);
 assert.equal((await call("/api/auth/logout",{method:"POST",cookie:managerCookie,body:{}})).status,200);assert.equal((await call("/api/auth/me",{cookie:managerCookie})).status,401);
 db.close();
});
