-- Additive calendar only; existing tables and rows remain unchanged.
CREATE TABLE calendar_sites(id TEXT PRIMARY KEY,name TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)),version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE calendar_user_sites(user_id TEXT NOT NULL,site_id TEXT NOT NULL REFERENCES calendar_sites(id),PRIMARY KEY(user_id,site_id));
CREATE TABLE calendar_vehicles(id TEXT PRIMARY KEY,name TEXT NOT NULL,plate TEXT NOT NULL DEFAULT '',type TEXT NOT NULL CHECK(type IN('Auto','Moto')),categories TEXT NOT NULL,transmission TEXT NOT NULL DEFAULT '',site_id TEXT NOT NULL REFERENCES calendar_sites(id),usual_site_id TEXT REFERENCES calendar_sites(id),status TEXT NOT NULL CHECK(status IN('DISPONIBILE','TRASFERIMENTO_PROGRAMMATO','IN_TRASFERIMENTO','MANUTENZIONE','NON_UTILIZZABILE','DISMESSO')),mileage REAL,version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE calendar_vehicle_movements(id TEXT PRIMARY KEY,vehicle_id TEXT NOT NULL REFERENCES calendar_vehicles(id),from_site_id TEXT NOT NULL REFERENCES calendar_sites(id),to_site_id TEXT NOT NULL REFERENCES calendar_sites(id),effective_at TEXT NOT NULL,mileage REAL,reason TEXT NOT NULL DEFAULT '',confirmed INTEGER NOT NULL DEFAULT 0 CHECK(confirmed IN(0,1)),actor_id TEXT NOT NULL,created_at TEXT NOT NULL,UNIQUE(vehicle_id,effective_at));
CREATE TABLE calendar_events(id TEXT PRIMARY KEY,event_type TEXT NOT NULL DEFAULT 'GUIDA' CHECK(event_type IN('GUIDA','ESAME')),meeting_point TEXT NOT NULL DEFAULT '',examiner TEXT NOT NULL DEFAULT '',write_token TEXT NOT NULL DEFAULT '',site_id TEXT NOT NULL REFERENCES calendar_sites(id),starts_at TEXT NOT NULL,ends_at TEXT NOT NULL,student_id TEXT,student_name TEXT NOT NULL,category TEXT NOT NULL,instructor_id TEXT NOT NULL,instructor_name TEXT NOT NULL,vehicle_id TEXT REFERENCES calendar_vehicles(id),note TEXT NOT NULL DEFAULT '',status TEXT NOT NULL CHECK(status IN('PROGRAMMATA','CONFERMATA','ANNULLATA','ASSENTE','SVOLTA','PROGRAMMATO','CONFERMATO','ANNULLATO','CONCLUSO')),deleted INTEGER NOT NULL DEFAULT 0 CHECK(deleted IN(0,1)),version INTEGER NOT NULL DEFAULT 1,created_by TEXT NOT NULL,updated_by TEXT NOT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,CHECK(starts_at<ends_at));
CREATE TABLE calendar_event_audit(seq INTEGER PRIMARY KEY AUTOINCREMENT,actor_id TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,action TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE INDEX calendar_events_site_time ON calendar_events(site_id,starts_at,ends_at);
CREATE INDEX calendar_events_resources ON calendar_events(instructor_id,vehicle_id,starts_at,ends_at);
CREATE TABLE calendar_event_instructors(event_id TEXT NOT NULL REFERENCES calendar_events(id),user_id TEXT NOT NULL,name TEXT NOT NULL,position INTEGER NOT NULL,PRIMARY KEY(event_id,user_id));
CREATE TABLE calendar_event_vehicles(event_id TEXT NOT NULL REFERENCES calendar_events(id),vehicle_id TEXT NOT NULL REFERENCES calendar_vehicles(id),name TEXT NOT NULL,position INTEGER NOT NULL,PRIMARY KEY(event_id,vehicle_id));
CREATE TABLE calendar_event_participants(event_id TEXT NOT NULL REFERENCES calendar_events(id),participant_key TEXT NOT NULL,student_id TEXT,name TEXT NOT NULL,position INTEGER NOT NULL,PRIMARY KEY(event_id,participant_key));
CREATE INDEX calendar_instructor_events ON calendar_event_instructors(user_id,event_id);
CREATE INDEX calendar_vehicle_events ON calendar_event_vehicles(vehicle_id,event_id);
CREATE INDEX calendar_participant_events ON calendar_event_participants(student_id,event_id);
CREATE INDEX calendar_movements_time ON calendar_vehicle_movements(vehicle_id,effective_at);
CREATE INDEX calendar_audit_actor_time ON calendar_event_audit(actor_id,created_at);
CREATE INDEX calendar_audit_entity ON calendar_event_audit(entity_type,entity_id,seq);
-- One internal assertion row; CHECK failures abort the whole D1 batch.
CREATE TABLE calendar_write_guard(id INTEGER PRIMARY KEY CHECK(id=1),conflict_ok INTEGER DEFAULT 1 CONSTRAINT CALENDAR_CONFLICT CHECK(conflict_ok=1),assignment_ok INTEGER DEFAULT 1 CONSTRAINT CALENDAR_ASSIGNMENT CHECK(assignment_ok=1),vehicle_ok INTEGER DEFAULT 1 CONSTRAINT CALENDAR_VEHICLE CHECK(vehicle_ok=1),transfer_ok INTEGER DEFAULT 1 CONSTRAINT CALENDAR_TRANSFER_CONFLICT CHECK(transfer_ok=1),rate_ok INTEGER DEFAULT 1 CONSTRAINT CALENDAR_RATE CHECK(rate_ok=1));
